Vagrantfile, deployment/ansible/group_vars/all, deployment/ansible/roles/nyc-trees.app/defaults/main.yml, src/nyc_trees/nyc_trees/settings/base.py
This changeset builds on the environmental variable virtual machine IP assignment by making IP address assignment to the application virtual machine occur via DHCP. In addition, the `NYC_TREES_TEST_DB_NAME` environmental variable provides a way to change the test database.
=> Add support for running Vagrant environments in parallel

deployment/ansible/roles/nyc-trees.app/tasks/log-rotation.yml
This changeset give the `nyc-trees` write permission to the application log file. Originally this was disabled because it was presumed that only the application service account would be writing logs. This isn't the case during local development (`vagrant` user).
Resolves: #254
---
```
$ ./scripts/debugserver.sh
+ vagrant ssh app -c 'sudo service nyc-trees-app stop || /bin/true'
Connection to 127.0.0.1 closed.
+ vagrant ssh app -c 'cd /opt/app/ && envdir /etc/nyc-trees.d/env gunicorn --config /etc/nyc-trees.d/gunicorn.py nyc_trees.wsgi'
^CConnection to 127.0.0.1 closed.
$ vagrant ssh app
Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-43-generic x86_64)
* Documentation:  https://help.ubuntu.com/
System information as of Tue Jan  6 16:12:37 UTC 2015
System load:  0.02 …
```
=> Make application log writable by owning group

deployment/ansible/group_vars/all, deployment/ansible/roles.txt, deployment/ansible/roles/nyc-trees.app/defaults/main.yml, deployment/ansible/roles/nyc-trees.app/meta/main.yml, deployment/ansible/roles/nyc-trees.nodejs/meta/main.yml, deployment/ansible/roles/nyc-trees.nodejs/tasks/main.yml
This changeset delegates the task of upgrading NPM to the Node.js role. Support for upgrading NPM was added in v0.3.0.
See also: https://github.com/azavea/ansible-nodejs/pull/4
=> Delegate NPM upgrade to Node.js role

src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/sass/partials/_groups.scss
This will force the group icons to have the same height and width.
Downside: forcing this using css means we need to specify a height and width. We'll need to use media queries to adjust this based on screen size, which is a bit of a pain, but not bad.
In terms of style, I suspect that these will change a bit once we are looking at some real logos, but this will prevent the "oval effect" for now.
=> Force square group images

src/nyc_trees/apps/home/routes.py, src/nyc_trees/apps/home/templates/flatpages/default.html, src/nyc_trees/apps/home/templates/home/training.html, src/nyc_trees/apps/home/urls.py, src/nyc_trees/apps/home/views.py, src/nyc_trees/nyc_trees/settings/base.py
To test:
* Run migrations
* In the Django admin, click "Add" next to "Flat Pages"
* Enter `/test/` for the `URL`, and some HTML content.
* Choose the only site, probably labeled `example.com`. (The name doesn't matter, but in production we should set it to the actual site name so users aren't confused.)
* Browse to the page you just created, at `/training/test`
=> Enable Django flatpages for training material

Vagrantfile, deployment/ansible/group_vars/development, deployment/ansible/group_vars/test
This changeset alters the changes made in #244 by accessing environmental variable directly in Ansible vs. funneling them through Vagrant's Ansible provisioner `extra_vars`.
The goal here is to avoid an edge case in how Vagrant passes `extra_vars` to the `ansible-playbook` command in a Windows/Cygwin environment.
Attempts to resolve #260.
=> Pull service virtual machine IP in Ansible vs. Vagrant

src/nyc_trees/nyc_trees/settings/test.py
This changeset adds an entry to `ALLOWED_HOSTS` so that the application UI can be viewed in test mode. My understanding is that test mode disables Django's debug mode, which triggers `ALLOWED_HOSTS` filtering.
=> Make application UI visible in test mode

deployment/ansible/roles.txt, deployment/ansible/roles/nyc-trees.beaver/meta/main.yml, deployment/ansible/roles/nyc-trees.beaver/tasks/main.yml, deployment/ansible/roles/nyc-trees.beaver/templates/django.conf.j2, deployment/ansible/roles/nyc-trees.beaver/templates/nginx.conf.j2, deployment/ansible/roles/nyc-trees.beaver/vars/main.yml, deployment/ansible/roles/nyc-trees.monitoring/meta/main.yml
This changeset adds support for Nginx and Django log shipping to the shared Logstash instance via Beaver. Nginx is already configured to emit its logs in JSON format. Beaver simply slurps them up and passes them along to Logstash. Django logs are shipped line-by-line unless they are a traceback, in that case the entire traceback is tucked into a single message.
=> Add support for log shipping to Logstash via Beaver

src/nyc_trees/.jshintrc, src/nyc_trees/apps/core/templates/core/settings.js, src/nyc_trees/apps/geocode/views.py, src/nyc_trees/apps/home/templates/home/partials/location_search.html, src/nyc_trees/apps/home/templates/home/progress.html, src/nyc_trees/js/src/ajaxLatest.js, src/nyc_trees/js/src/geocoder.js, src/nyc_trees/js/src/map.js, src/nyc_trees/js/src/mapUtil.js, src/nyc_trees/js/src/progressPage.js, src/nyc_trees/js/src/searchController.js, src/nyc_trees/nyc_trees/context_processors.py, src/nyc_trees/nyc_trees/settings/base.py
The geocode interface is split into three layers:
The geocode interface is split into three layers:
1. A generic ``ajaxLatest`` module that allows for interruptible requests.
2. A wrapper around the geocode AJAX requests that converts responses to events.
3.  A controller that pulls markup from template script tags and manages the display of UI elements in response to user events and geocode events.
To keep the ``map`` module lean, I moved a lot of code initially written in that module out to ``searchController``, but I needed access to map zooming helpers that were initially added to ``map``. My solution was to move the helpers out to a new ``mapUtils`` module.
I consulted @jfrankl on the mechanics of how to display the search controls, error messages, and results. The generated markup …
=> Add geocoder interface to map module

src/nyc_trees/apps/core/views.py
The JS settings view was recently moved out of the urls file into a proper view function. The new view pipeline was no longer returning the correct content-type header and was not running the context processors. This commit restores those items.
=> Fix settings.js view

scripts/vagrant-env.sh, scripts/vagrant-up.sh
This changeset adds a script that wraps the Vagrant provisioning process inside of an exponential backoff function. The first failure waits 5 seconds, second waits 10, and third waits 20.
The goal of this changeset is to get past transient failures we encounter in CI that cause the entire build to fail.
=> Add exponential backoff script for CI interactions with Vagrant

deployment/ansible/roles/nyc-trees.beaver/tasks/main.yml, deployment/ansible/roles/nyc-trees.beaver/templates/windshaft.conf.j2, src/tiler/server.js
This changeset adds support for Windshaft log shipping via Beaver to the shared Logstash instance and populates the StatsD configuration in Windshaft.
=> Add support for capturing Windshaft logs and metrics

deployment/ansible/roles.txt
This changeset fixes a missing `python-docutils` dependency required by Beaver. It is still unclear what caused this regression. Beaver appeared to be installing cleanly last week.
Attempts to resolve #290.
(Sorry for the back-to-back PRs, Steve.)
=> Use updated Beaver role with support for installing docutils

src/nyc_trees/gulpfile.js
We want the gulp process to have an non-zero exit code if there is a problem with bundling.
There may be a better, or more generic way to do this, but this catches our most recent problem.
=> Crash gulp build if browserify fails

deployment/ansible/group_vars/all, deployment/ansible/roles.txt
This changeset updates the PostGIS Ansible role to avoid having PostgreSQL 9.3 and 9.4 installed on the services VM.
See also: https://github.com/azavea/ansible-postgis/pull/3
=> Bump version of PostGIS Ansible role

deployment/ansible/roles.txt
This changeset bumps the version of Kibana used to query the Logstash index to 4 beta 3.
See also: https://github.com/azavea/ansible-kibana/pull/3
=> Use updated Kibana role with support for version 4 beta 3

src/nyc_trees/apps/survey/models.py, src/nyc_trees/apps/users/routes/group.py, src/nyc_trees/apps/users/urls/group.py, src/nyc_trees/apps/users/views/group.py
Does not attempt to cluster disjoint groups of blockfaces into separate
polygons.
After some research, it seems like the best course of action *may* be to
manually create polygons for those groups which have disjoint territories.
=> Add endpoint for calculating GeoJSON polygon of a group's territory

deployment/ansible/roles.txt
This changeset addresses the `python-daemon` installation issues that were failing the Beaver installation.
See also: https://github.com/azavea/ansible-beaver/pull/3
=> Bump Ansible Beaver role to 0.1.2

deployment/ansible/roles/nyc-trees.app/tasks/dev-and-test-dependencies.yml
This changeset uses APT globbing support to relax the version specification associated with Firefox and Xvfb.
Attempts to resolve: #320
=> Glob Firefox and Xvfb test dependencies

src/nyc_trees/apps/core/templates/core/partials/config.js, src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html, src/nyc_trees/js/src/map.js, src/nyc_trees/js/src/mapUtil.js, src/nyc_trees/js/src/progressPage.js, src/nyc_trees/js/src/reservationPage.js, src/nyc_trees/nyc_trees/context_processors.py, src/nyc_trees/nyc_trees/tests.py, src/tiler/files.js, src/tiler/server.js, src/tiler/sql/user_reservable.sql, src/tiler/style/progress.mss
To guide a person in selecting blocks to add to their reservation, we need a simple available/not available layer.
I am adding this to the initial view of the reservation page for bootstrapping purposes only. When the "add" mode is implemented, it will show this layer only in that mode.
To implement this, I refactored the tile server and config context processor to be easily extensible.
=> Add reservable layer

scripts/vagrant-up.sh
This changeset tries to address the scenario where a `vagrant provision` on a halted virtual machine returns an exit status of 0. Now a step to bring up the specific virtual machine is wrapped in an exponential backoff function along with the provisioning step. If bringing the virtual machine up fails, provisioning will never be attempted.
Attempts to resolve: #297
=> Fix Vagrant provision false positive

README.md, Vagrantfile, deployment/ansible/app-servers.yml, deployment/ansible/filter_plugins/custom_filters.py, deployment/ansible/group_vars/all, deployment/ansible/group_vars/packer, deployment/ansible/monitoring-servers.yml, deployment/ansible/roles/nyc-trees.app/meta/main.yml, deployment/ansible/roles/nyc-trees.app/tasks/app.yml, deployment/ansible/roles/nyc-trees.app/tasks/configuration.yml, deployment/ansible/roles/nyc-trees.app/tasks/dependencies.yml, deployment/ansible/roles/nyc-trees.app/tasks/main.yml, deployment/ansible/roles/nyc-trees.app/tasks/static-files.yml, deployment/ansible/roles/nyc-trees.app/templates/gunicorn-nyc-trees.py.j2, deployment/ansible/roles/nyc-trees.app/templates/upstart-nyc-trees-app.conf.j2, deployment/ansible/roles/nyc-trees.collectd/default/main.yml, deployment/ansible/roles/nyc-trees.collectd/templates/write_graphite.conf.j2, deployment/ansible/roles/nyc-trees.common/meta/main.yml, deployment/ansible/roles/nyc-trees.common/tasks/main.yml, deployment/ansible/roles/nyc-trees.graphite/templates/write_graphite.conf.j2, deployment/ansible/roles/nyc-trees.tiler/meta/main.yml, deployment/ansible/roles/nyc-trees.tiler/tasks/app.yml, deployment/ansible/roles/nyc-trees.tiler/tasks/configuration.yml, deployment/ansible/roles/nyc-trees.tiler/tasks/main.yml, deployment/ansible/roles/nyc-trees.tiler/templates/upstart-nyc-trees-tiler.conf.j2, deployment/ansible/services.yml, deployment/ansible/tile-servers.yml
This pull request contains two commits because I couldn't get the refactoring to work without the addition of the customer filters.
One commit adjusts the shared dependencies between the application and tiler so that they exist in one place (`nyc-trees.common`). The other adds custom filters to help determining a node's group membership.
=> Refactor app and tiler dependencies and add filter plugins

README.md, Vagrantfile, deployment/Makefile, deployment/README.md, deployment/ansible/roles/nyc-trees.app/defaults/main.yml, deployment/deployment-helper.sh, deployment/packer/template.js, deployment/troposphere/app_hosted_zone_template.py, deployment/troposphere/app_template.py, deployment/troposphere/data_store_template.py, deployment/troposphere/tiler_hosted_zone_template.py, deployment/troposphere/tiler_template.py, src/nyc_trees/nyc_trees/settings/base.py, src/nyc_trees/nyc_trees/settings/production.py, src/nyc_trees/requirements/production.txt
This changeset adds blue/green deployment support to the tiler with:
- AMI building
- Blue/green CloudFormation stacks
- Toggling between stacks through a CloudFront origin
In addition, the Django application uses DNS resolution (CNAME record) against `tile.service.nyc-trees.internal` to determine its tile host (ultimately, the CloudFront distribution endpoint). The process for toggling between stacks alters the origin of the CloudFront distribution.
=> Add blue/green deployment support to tiler

src/nyc_trees/sass/partials/_globals.scss
Not sure how these got back in globals, but this all needs to get deleted.
=> Remove redundant css that is also in _map.scss

src/nyc_trees/apps/survey/views.py
The "current" reservations should reflect how many blockfaces are
selected on the page, not how many blockfaces are reserved.
=> Fix bug with new reservations counts

deployment/ansible/roles/nyc-trees.app/templates/nginx-nyc-trees-app.conf.j2, deployment/ansible/roles/nyc-trees.tiler/templates/nginx-nyc-trees-tiler.conf.j2
This changeset adds HTTP caching support to production deployments by:
- Enabling the Cache-Control, Expires, and ETag headers for static assets
- Enabling the Cache-Control and Expires headers for tiles
It is worth noting that when the tiler is fronted by CloudFront, CloudFront will choose the greater of Cache-Control vs. 24 hours, but reserves the right to purge infrequently accessed assets from edge locations to make way to more frequently accessed ones.
Attempts to resolve #302 and #303.
=> Add HTTP caching support for tiles and static assets

deployment/ansible/roles/nyc-trees.pgweb/templates/pgweb.conf.j2, deployment/ansible/roles/nyc-trees.postgresql/tasks/main.yml, deployment/ansible/roles/nyc-trees.postgresql/templates/postgresql.j2
This changeset sets the Upstart `start on` stanza for `pgweb` to depend on a `initctl` event emitted by the PostgreSQL `init.d` script.
=> Fix pgweb startup sequence after boot

src/nyc_trees/nyc_trees/settings/production.py
We want to exercise the full application in our staging environment (which uses production settings) but can't with this flag set to True. The plan is to replace this simple settings flag with a database-backed system with finer grained control over "on" and "off."
=> Disable soft launch until better setting available

src/nyc_trees/nyc_trees/settings/base.py
This changeset adds a `DEFAULT_FROM_EMAIL` setting with the Azavea domain so that it is not rejected by Amazon SES.
Attempts to resolve: https://github.com/azavea/nyc-trees/issues/392
=> Add DEFAULT_FROM_EMAIL

deployment/ansible/group_vars/all
This changeset sets the package version of RELP to the highest version that begins with `7.4.4`.
=> Add glob to RELP package version

src/nyc_trees/js/src/reserveBlockfacePage.js
This appeared to work when I first tested it but Objects don't have a
length property, obviously. Also, suppress an error when clicking empty
spaces on the map.
=> Fix errors on reserve blockface page

deployment/troposphere/app_template.py, deployment/troposphere/tiler_template.py
This changeset adds CloudWatch alarms to the application and tiler Elastic Load Balancers (ELBs). The two  metrics right now are backend 4XX and 5XX failures.
=> Add CloudWatch alarms to the application and tiler ELBs

src/nyc_trees/apps/core/decorators.py, src/nyc_trees/apps/core/helpers.py, src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/event/templates/event/partials/rsvp.html, src/nyc_trees/apps/home/templates/home/training_instructions.html, src/nyc_trees/apps/home/training/routes.py, src/nyc_trees/apps/home/training/views.py, src/nyc_trees/apps/home/urls.py
This alters the `user_must_have_online_training` decorator and redirects users to a "training instructions" page if they try to RSVP for an event before they have completed training.
Refs #405
=> Require that users complete training before they can RSVP for an event

deployment/ansible/group_vars/all
This changeset extends the glob for the version number of PostgreSQL related packages so that the minor version is included. Originally, the minor version was being included because the version of PostgreSQL being used in RDS is `9.5.3`.
Attempts to resolve: #453
=> Unpin minor version of PostgreSQL related packages

deployment/deployment-helper.sh, deployment/troposphere/data_store_template.py
This changeset gives the monitoring server a subdomain off of the default Route 53 hosted zone.
For example, if the default hosted zone is `treescount.foo.com`, these CloudFormation changes will create an A record of `monitoring.treescount.foo.com` under the `treescount.foo.com` hosted zone that points to the public IP address of the monitoring server.
=> Add DNS support for monitoring server

src/nyc_trees/sass/partials/_header.scss, src/nyc_trees/sass/partials/_home.scss, src/nyc_trees/sass/partials/_map.scss, src/nyc_trees/sass/partials/_variables.scss
I was having a lot of trouble getting Bootstrap modals to work properly,
because the z-index values in our SCSS was significantly higher than
Bootstrap's.
This moves most of z-index values to be based off of variables, defined
directly below the Bootstrap z-index definitions, and lowers all z-index
values where appropriate.
I also removed several z-index properties altogether because I could not
determine what effect, if any, they had.
=> Clean up z-index values to be lower than Bootstrap's

src/nyc_trees/apps/core/templates/base.html, src/nyc_trees/apps/survey/models.py, src/nyc_trees/apps/survey/routes.py, src/nyc_trees/apps/survey/templates/survey/partials/reserved_blockface_popup.html, src/nyc_trees/apps/survey/templates/survey/reservations.html, src/nyc_trees/apps/survey/views.py, src/nyc_trees/js/src/reservationPage.js, src/nyc_trees/nyc_trees/context_processors.py
Clicking "Cancel This" from the action bar will open a Bootstrap modal
After clicking "Cancel Reservation" on the modal, the reservation is canceled
on the backend, and tile/grid layers are updated on the client.
There are known issues with the legend in desktop mode interfering with the cancel modal that will be fixed by #463
=> Add ability to cancel reservations

deployment/troposphere/template_utils.py, deployment/troposphere/vpc_template.py
This changeset adds HVM AMI support to the NAT instances, which allows us to use `t2.*` instance types vs. the previous `t1.micro`.
=> Add support for HVM NAT instances

deployment/ansible/roles/nyc-trees.app/tasks/dependencies.yml
This changeset adds globs to the versions of the geospatial libraries used by the Django application.
=> Add conservative globs to the geospatial libraries dependencies

deployment/deployment-helper.sh, deployment/troposphere/data_store_template.py
This changeset switches our default EBS volume types from `standard` (AKA magnetic) to `gp2` (AKA general purpose SSD) by using an SSD based AMI.
See also: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html
=> Add support for EBS volume SSD storage

src/nyc_trees/apps/survey/templates/survey/partials/reserve_blockface_modals.html, src/nyc_trees/apps/survey/templates/survey/reservations.html, src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html, src/nyc_trees/apps/users/routes/group.py, src/nyc_trees/apps/users/templates/groups/settings.html, src/nyc_trees/apps/users/urls/group.py, src/nyc_trees/apps/users/views/group.py, src/nyc_trees/js/src/reserveBlockfacePage.js, src/tiler/server.js, src/tiler/sql/user_reservable.sql
Click on unavailable blockfaces to request group mapper status.
How to test:
1. Restart tiler and rebuild JS
2. Enable `individual_mapper` on your test user
3. Go to the "new reservations" page [http://localhost:8000/blockface/reserve/](http://localhost:8000/blockface/reserve/)
3. If a group has `allows_individual_mappers` disabled, when you click on blocks, you should get a generic error message.
4. If a group has `allows_individual_mappers` enabled, when you click on blocks, you should get a popup that asks if you would like to request permission for group mapper status.
5. The mapper status request should appear on the group admin page [http://localhost:8000/group/east-side/edit/](http://localhost:8000/group/east-side/edit/) (replace group name)
=> Request mapper status

src/nyc_trees/js/src/searchController.js
I talked over our options with @jfrankl and made two changes to make location search more useful on small mobile phones.
1. The status message is hidden when there are multiple results. The
message was not helpful and it now allows an extra result to be
shown.
2. The search UI is hidden automatically after zooming to a result. This
allows more of the map to be visible. It is not likely that a
person will immediately search again and, if they do, making them tap
the search toolbar button again is worth the extra space gained in
trade.
Fixes #507 
Fixes #509
=> Make location search UI take up less space

src/nyc_trees/sass/partials/_header.scss
Safari desktop and mobile is rendering the .overlay-menued div on top of the sidebar, which hijacks all link clicking. Setting left: to the same width as the sidebar fixes the issue in Safari and still works in other browsers.
Fixes #505
=> Set left on sidebar overlay to fix Safari issue

README.md, Vagrantfile, deployment/ansible/group_vars/all, deployment/ansible/group_vars/development, deployment/ansible/group_vars/monitoring-servers, deployment/ansible/group_vars/packer, deployment/ansible/monitoring-servers.yml, deployment/ansible/roles.txt, deployment/ansible/roles/nyc-trees.tasseo/meta/main.yml, deployment/ansible/roles/nyc-trees.tasseo/tasks/main.yml, deployment/ansible/roles/nyc-trees.tasseo/templates/nyc-trees.js.j2, deployment/ansible/services.yml, deployment/troposphere/data_store_template.py, src/nyc_trees/nyc_trees/settings/base.py
This changeset adds support for Tasseo, which is a dashboard for highlighting select Graphite metrics. As of right now, the only metrics highlighted are:
- Django response codes
- E-mail success/failures
- Windshaft success/failures
=> Add Tasseo as a dashboard for select Graphite metrics

src/nyc_trees/sass/partials/_globals.scss, src/nyc_trees/sass/partials/_header.scss
Justin,
This should increase the scrolling speed on iOS (and all devices). I removed all fixed elements, which were causing the browser to repaint the entire window, since they were in moving elements.
More information here:
https://remysharp.com/2012/05/24/issues-with-position-fixed-scrolling-on-ios
I can try adding the css you suggested if this doesn't do it.
=> Drastically reduce dom repainting; Fixes #528 (I think)

src/nyc_trees/apps/core/mail/backends/boto.py
This fixes an error caused by sending emails using the Boto backend on
staging/production. Django email backends must accept a variable
number of arguments.
Fixes #482
=> Fix server error when resetting password on staging

src/nyc_trees/apps/core/decorators.py, src/nyc_trees/apps/core/migrations/0015_auto_20150213_1321.py, src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/core/templates/core/partials/nav.html, src/nyc_trees/apps/home/routes.py, src/nyc_trees/apps/home/templates/home/individual_mapper_instructions.html, src/nyc_trees/apps/home/urls.py, src/nyc_trees/apps/home/views.py, src/nyc_trees/apps/users/__init__.py, src/nyc_trees/apps/users/routes/user.py, src/nyc_trees/apps/users/templates/users/partials/activity.html, src/nyc_trees/apps/users/urls/group.py, src/nyc_trees/apps/users/views/user.py, src/nyc_trees/js/src/reserveBlockfacePage.js, src/nyc_trees/nyc_trees/context_processors.py, src/nyc_trees/nyc_trees/settings/base.py
Once a user has completed online training, attended 1 training event, and 1 other event, they should see a button on their user profile to request individual mapper status. When clicked, this button will immediately grant access to the reservations page and the ability to reserve blockfaces.
Migrations must be run for testing.
See #517 for a description of the workflow that should be followed for verification purposes.
=> Add individual mapper status workflow

src/nyc_trees/apps/core/templates/core/partials/config.js, src/nyc_trees/js/src/event_form.js
fixes #484 on github
The build tooling replaces occurrences of this filename with a modified
version that has a snippet of a sha attached to it. We use this filename
as a key in configuration and it caused a failed key lookup.
=> Don't use filename as a key in javascript

src/nyc_trees/apps/event/forms.py, src/nyc_trees/requirements/base.txt
The date fields are passed in to the ``clean`` method as they appear on the form, which means they will always be Eastern US time. We need to convert now() to Eastern US time before doing any comparisons.
=> Validate event dates using Eastern not UTC

src/nyc_trees/apps/home/templates/home/training_instructions.html
Since we can link directly to the event tabs via query string, we don't have
to do any additional work to support tab hash on the events page.
Closes #523
=> Link directly to training events from training instructions page

src/nyc_trees/apps/event/templates/event/partials/event_form.html, src/nyc_trees/templates/registration/activation_complete.html
These errors will be shown on top of the specific field, so we shouldn't
show them again above the entire form.
Fixes #331
=> Don't show field errors at the top of the event form.

src/nyc_trees/apps/users/templates/groups/detail.html
A button that goes nowhere is confusing to a person viewing the group detail page.
Fixes #553
=> Hide group URL on detail page if not set

src/nyc_trees/apps/event/templates/event/partials/rsvp.html, src/nyc_trees/apps/home/templates/home/training_instructions.html
Users must complete online training before they can attend a training
event. Now, when the user tries to RSVP for a training event before
completing the online training, they will be forwarded to the training
instructions page.
Fixes #521 
1. Login as a user with no field/online training
2. RSVP to a Mapping event (should redirect to training instructions)
3. RSVP to Training event (should redirect to training instructions)
4. Complete online training steps
5. RSVP to a Mapping event (should redirect to training instructions)
6. RSVP to Training event (should RSVP you to that event)
=> Fix 403 error when RSVP-ing for training event

src/nyc_trees/apps/users/routes/group.py, src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/apps/users/templates/groups/partials/follow_detail.html, src/nyc_trees/apps/users/views/group.py, src/nyc_trees/js/src/fetchAndReplace.js, src/nyc_trees/js/src/group_detail.js, src/nyc_trees/js/src/group_list.js
This commit adds the correct follower count to the group detail page.
Updating the count when a person clicks the "Follow" button required changing the follow/unfollow views and responses, but the change had to be "backward compatible," since the group list page shows follow/unfollow buttons without counts. To implement this, I added a POST argument that is fed through to the template which then decides whether the button should be rendered alone, or with a count next to it.
=> Include updating follow count on group detail

src/nyc_trees/js/src/group_detail.js
If a group has no territory, we were not creating the "map" element, but
still trying to initialize the leaflet map.
Fixes #585
=> Only initialize group detail map if it has territory.

src/nyc_trees/apps/survey/views.py, src/tiler/sql/user_reservations.sql
An individual mapper will have at most 20 blockfaces reserved at any given time. This left us with a largely empty reservation map, so we decided to show the other blockfaces as unavailable.
Fixes #566
=> Show all blockfaces on reservation page

src/nyc_trees/apps/core/helpers.py, src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/apps/users/urls/group.py, src/nyc_trees/apps/users/views/group.py, src/nyc_trees/js/src/group_detail.js
How to test:
1. Select a group that allows individual mappers
2. Login as a non-group admin that is not a trusted mapper (for your test group)
3. Go to the group detail page
4. You should see a "Request Individual Mapper" button
5. Clicking this button should create a new mapper request in the Group Admin page
6. When a group admin approves this request, the button should disappear from the group detail page
=> Wire up "Request Individual Mapper Status" button on group detail page

src/nyc_trees/apps/core/templates/base.html, src/nyc_trees/apps/core/templates/base_map.html, src/nyc_trees/apps/core/templates/base_reservation.html, src/nyc_trees/apps/event/templates/event/event_list_page.html
The footer is excluded from full screen map page to maximize the viewable area.
Fixes #601
Fixes #516
=> Add footer to non-map pages

deployment/packer/template.js
This changeset adds the following tags to all AMIs:
- Created (human-readable timestamp of when the AMI was created)
- Service (name of the service this AMI contains)
- Environment (target environment for this AMI)
---
**Example of AMI tagging**:
=> Add more detailed tags to AMIs

src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/core/templates/core/partials/nav.html, src/nyc_trees/apps/survey/routes.py, src/nyc_trees/apps/survey/templates/survey/reservations.html, src/nyc_trees/apps/survey/urls/blockface.py, src/nyc_trees/apps/survey/views.py, src/nyc_trees/nyc_trees/context_processors.py, src/nyc_trees/nyc_trees/settings/base.py
Add "Reservations" link back to the side nav and also adds some instructions on how to become an individual mapper.
1. Login as a non-individual mapper user
2. Go go Reservations page
3. Click New (should go to instructions page)
4. Grant user individual mapping status
5. Go go Reservations page
6. Click New (should go to reserve blockface page)
=> Show reservations link in side nav

src/nyc_trees/apps/core/helpers.py, src/nyc_trees/apps/users/views/group.py
Fixes:
Internal Server Error: /group/american-hornbeam-appreciation-society/
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 33, in routed
return req_method(request, *args2, **kwargs2)
File "/opt/app/apps/core/decorators.py", line 32, in wrapper
return view_fn(request, *args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/django_tinsel/decorators.py", line 79, in wrapper
params = callable_or_dict(request, *args, **wrapper_kwargs)
File "/opt/app/apps/users/views/group.py", line 77, in group_detail
show_mapper_request = …
=> Fix exception when viewing group detail page logged out

src/nyc_trees/apps/event/templates/event/partials/event_section.html
This restores hidden form fields needed on the user profile page.
Broken by 7c543f46e7f82557187e057e2c178090e46fd81c.
This is not a priority for user testing.
Fixes #633
=> Fix error when saving user profile

deployment/ansible/roles/nyc-trees.app/defaults/main.yml, deployment/ansible/roles/nyc-trees.app/tasks/log-rotation.yml, deployment/ansible/roles/nyc-trees.app/templates/gunicorn-nyc-trees.py.j2, deployment/ansible/roles/nyc-trees.app/templates/logrotate-nyc-trees-gunicorn.j2, deployment/ansible/roles/nyc-trees.app/templates/upstart-nyc-trees-app.conf.j2, deployment/ansible/roles/nyc-trees.beaver/tasks/main.yml, deployment/ansible/roles/nyc-trees.beaver/templates/gunicorn.conf.j2
This changeset ensures that the Django specific logs go into `/var/log/nyc-trees-app.log`, while the Gunicorn specific logs go into `/var/log/nyc-trees-gunicorn.log`. Log shipping and rotation for the new logs was also added.
Previously, Django application logs were leaking out of the Upstart job, which got redirected automatically to `/var/log/upstart/nyc-trees-app.log`. Now those logs are in `/var/log/nyc-trees-app.log`.
=> Fix Django application logs; add Gunicorn specific log

src/nyc_trees/apps/event/templates/event/partials/event_form.html
It looks like this was somewhat fixed by recent design changes. I moved
the validation message outside of the input div so that the error
message does not increase the length of the input field.
Also, I swapped field labels/errors because IMO it makes it much clearer to
see which form fields the errors are talking about.
There is remaining work to style validation messages.
This is not a priority for user testing.
Fixes #492
=> Fix layout issue when error message is displayed

src/nyc_trees/apps/event/views.py
This fixes an edge case where, if a group admin RSVPs to their own
event, and then clicks the "Starting soon" header notification, they
are taken to the user checkin page rather than the admin checkin page.
This is not a priority for user testing.
Fixes #526
=> Redirect group admin to admin event checkin page

deployment/ansible/roles/nyc-trees.tasseo/templates/nyc-trees.js.j2
This changeset fixes the metric name used by Tasseo for e-mail graphs. Because `django-statsd` handles the StatsD client setup, all metrics that come through the following import get tucked under the `django` metric namespace:
```python
from django_statsd.clients import statsd
```
Attempts to resolve #636.
=> Fix metric name used by Tasseo for e-mail graphs

deployment/ansible/roles/nyc-trees.app/templates/nginx-nyc-trees-app.conf.j2, deployment/ansible/roles/nyc-trees.common/meta/main.yml, deployment/ansible/roles/nyc-trees.nginx/meta/main.yml, deployment/ansible/roles/nyc-trees.nginx/tasks/main.yml, deployment/ansible/roles/nyc-trees.nginx/templates/log-format.conf.j2, deployment/ansible/roles/nyc-trees.tiler/templates/nginx-nyc-trees-tiler.conf.j2
This changeset moves the Nginx `log_format` directive into the `http` block (via an include). The newly created `nyc-trees.nginx` role handles providing the `logstash_json` format for application server and tiler `server` blocks to use.
This also prevents Nginx errors citing that `log_format` must be defined in the `http` block.
=> Centralize Nginx log_format directive

deployment/README.md, deployment/ansible/roles/nyc-trees.app/templates/nginx-nyc-trees-app.conf.j2, deployment/deployment-helper.sh, deployment/troposphere/app_template.py
This changeset adds HTTPS support to the application server stack by:
- Associating a certificate ARN with the load balancer
- Accepting connections on load balancer port 443
- Ensuring Nginx redirects inbound HTTP requests to HTTPS
- Add health-check endpoint as an exception to the line item above
=> Add HTTPS support for the application server stack

src/nyc_trees/apps/survey/layer_context.py, src/nyc_trees/apps/survey/views.py, src/tiler/sql/user_reservable.sql
Group admins should not have to go through the trusted mapper workflow
in order to reserve blockfaces in their own territory.
=> Group admin should always be able to reserve blockfaces

src/nyc_trees/js/src/surveyPage.js
Update `blockfaceId` when user clicks a blockface. Fixes #681.
=> Fix survey page for arrival via reservation checkout page

src/nyc_trees/apps/event/forms.py, src/nyc_trees/apps/event/models.py
Switches to testing against 'ends_at' instead of 'begins_at', to allow
editing events that are in progress.
Also allows editing past events, provided that the times have not been
changed.
Fixes #564
=> Allow editing past or in progress events.

src/nyc_trees/apps/core/admin.py, src/nyc_trees/apps/core/models.py
This fixes an issue where you are unable to modify user passwords via
the Django admin.
Reference:
http://stackoverflow.com/questions/15012235/using-django-auth-useradmin-for-a-custom-user-model
Fixes #130
Not a priority for sprint review.
=> Add custom admin for User model

src/nyc_trees/apps/survey/migrations/0009_blockface_expert_required.py, src/nyc_trees/apps/survey/models.py
The block faces we will be importing include a flag that indicates when the block face may be too difficult to be mapped accurately by the general public. We will not be using this flag at "runtime" but adding it to our blockface model makes it easy to bulk-assign these blocks as territory owned by the NYC Parks group.
=> Add expert_required to survey_blockface

src/nyc_trees/js/src/surveyPage.js
Should be very useful when mapping blocks at an event.
=> Show geolocation button on the survey page.

src/nyc_trees/apps/survey/layer_context.py, src/nyc_trees/apps/survey/routes.py, src/nyc_trees/apps/survey/templates/survey/admin_territory.html, src/nyc_trees/apps/survey/urls/census_admin.py, src/nyc_trees/apps/survey/views.py, src/nyc_trees/gulpfile.js, src/nyc_trees/js/src/adminTerritoryPage.js, src/nyc_trees/js/src/map.js, src/tiler/server.js, src/tiler/sql/group_territory_admin.sql
Show these categories of blockface:
* Available
* Reserved by this group
* Reserved by others
* Mapped by this group
* Mapped by others
These are essentially the same categories as shown on the "Reservations" page.
Initially we thought all of the following should be shown as "unavailable":
* Reserved by others
* Mapped by this group
* Mapped by others
I wanted to
* distinguish "Mapped by this group" to give context when working on a group,
for example if you want to grow territory contiguously.
* distinguish "Reserved by others" from "Mapped by others" to allow seeing
what yet needs to be mapped in a reapportioning situation.
With good coloring I think these will be useful and not distracting.
And it's easy to go back to 3 categories if we prefer.
Also:
* Fix omission of …
=> Admin page for managing group territory

src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/js/src/lib/valIsEmpty.js, src/nyc_trees/js/src/surveyPage.js
This change set allows a mapper to "bail out" of a survey, and forces them to leave an explanation as to why they are quitting. I have opted to not post any tree data because it could be invalid, and it could be frustrating to a person who is trying to stop mapping if we force them to make data corrections first.
What happens after the quit has been POSTed is left as a TODO because that part of the workflow is in progress.
To test:
1. Log in as an individual mapper
1. Reserve a block face
1. Start mapping, select the block, end, and side of the street.
1. Scroll to the bottom of the survey form and click "I cannot map this block"
There should be a popup with a text area. You should not be able to click "Stop Mapping" until there is non-whitespace content in the text area.
=> Add a popup for exiting a survey without mapping

src/nyc_trees/apps/survey/views.py, src/nyc_trees/apps/users/routes/group.py, src/nyc_trees/apps/users/urls/group.py, src/nyc_trees/apps/users/views/group.py, src/nyc_trees/js/src/adminTerritoryPage.js
* Endpoint `group_unmapped_territory_geojson`
* Click blockfaces to select/deselect individually
* Explain unselectable blockfaces via toast
Also:
* Sort groups by name in drop-down
* Show the first group's territory on page load
=> Selectable layer for unmapped group territory

src/nyc_trees/apps/core/helpers.py, src/nyc_trees/apps/core/migrations/0016_remove_user_is_census_admin.py, src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/users/tests.py, src/nyc_trees/apps/users/uitests.py
Since Census Admins will need to have access to the Django Admin
site anyways, it makes sense to consolidate these flags into 1.
Fixes #75
=> Remove is_census_admin in favor of using builtin is_superuser.

src/nyc_trees/js/src/map.js
Prior to this fix, bounds and location were failing for maps that didn't
have the standard dom id of 'map'.
=> Fix bounds and location in map module

deployment/ansible/group_vars/development
This changeset allows Vagrant users to connect to the PostgreSQL database from the virtual machine host via the port forwarded `15432`.
=> Add IP address range for eth0 to PostgreSQL HBA

src/nyc_trees/apps/core/admin.py
This was causing the Django Admin pages to crash.
Fixes #731
=> Remove reference to removed user field is_census_admin.

src/nyc_trees/apps/survey/templates/survey/admin_territory.html, src/nyc_trees/apps/users/routes/group.py, src/nyc_trees/apps/users/views/group.py, src/nyc_trees/css/leaflet.draw.css, src/nyc_trees/js/src/adminTerritoryPage.js, src/nyc_trees/js/src/lib/SelectableBlockfaceLayer.js, src/nyc_trees/npm-shrinkwrap.json, src/nyc_trees/package.json
* Bring in `leaflet-draw`
* Add instructions, controls, and tool tips for polygon drawing
* If `group_unmapped_territory_geojson` endpoint gets an optional polygon, return
both current and available territory contained in the polygon
Enhance `SelectableBlockfaceLayer.js`
* Allow specifying `onAdded` handler, called when a feature is actually added
* Add `clicksEnabled` property to enable/disable click handling
In `adminTerritoryPage.js`:
* Handle polygon drawing events
* Keep currently-selected blockfaces in `selectedBlockfaces` object
(which maps a blockface ID to its displayed feature layer)
* While drawing a polygon, disable clicking on blockfaces
* When polygon complete, fetch contained blockfaces and update selection (add or remove)
* "Revert" button resets selection to group's saved …
=> Modify group territory by drawing a polygon

deployment/ansible/roles.txt, deployment/ansible/roles/nyc-trees.app/meta/main.yml, scripts/test.sh
This changeset adds PhantomJS to the application server via the PhantomJS Ansible role.
See also: https://github.com/azavea/ansible-phantomjs
=> Add PhantomJS to application server

scripts/dump_blockfaces.sh, src/nyc_trees/apps/survey/management/commands/assign_expert_blocks.py
We are receiving the production blockface data in chunks. I have updated the fixture with the production Manhattan blockfaces.
``dump_blockfaces.sh`` serves to document the process of dumping the content of the survey_blockface table into a known file which is loaded by setupdb.sh
Parks wants to assign all the "difficult" blocks to a group so that only skilled users can reserve and map them. This command idempotently assigns any blockface with ``expert_required == True`` to a specified group, possibly deleting a previous assignment to another group.
=> Update blockface fixture and add scripts for blockface management

src/nyc_trees/apps/event/templates/event/event_list_page.html, src/nyc_trees/apps/home/templates/home/training.html, src/nyc_trees/apps/users/templates/groups/list.html, src/nyc_trees/sass/partials/_globals.scss, src/nyc_trees/sass/partials/_map.scss
This brings back page mobile descriptions for the groups, events, and training pages.
More work is needed to do this on map-based pages.
=> Show page descriptions on mobile

src/nyc_trees/apps/event/event_list.py, src/nyc_trees/apps/event/templates/event/event_list_page.html, src/nyc_trees/apps/event/templates/event/partials/event_list.html
This prevents old events from appearing on the Dashboard and the Events page.
Fixes #622 and #673.
=> Fix old events appearing where they shouldn't

scripts/aws/setupdb.sh
Getting from `scripts/aws/` to `src/` requires `../../`, not `../`
=> Fix fixture pathnames

src/tiler/sql/user_reservations.sql
Once a block is surveyed we flip ``is_available`` to false. The layer we use to show mappers their options should show completed blocks as unavailable.
Fixes #723 
Fixes #764
=> Only show available blocks on survey layer

src/tiler/sql/user_reservations.sql
In a previous commit I changed the color of the block but forgot to extend the filtering to the UTF grid.
Fixes #776
=> Prevent selecting unavailable blocks on survey

src/nyc_trees/apps/survey/layer_context.py, src/nyc_trees/apps/survey/templates/survey/admin_territory.html, src/nyc_trees/apps/survey/views.py, src/nyc_trees/apps/users/routes/group.py, src/nyc_trees/apps/users/urls/group.py, src/nyc_trees/apps/users/views/group.py, src/nyc_trees/js/src/adminTerritoryPage.js, src/nyc_trees/js/src/map.js
* "Save" button posts currently-selected blockface ids to `group_update_territory` endpoint,
which adds/removes appropriate `Territory` records.
* We need new tiler URLs after saving. So, change to return full tiler URLs along with
Ajax data instead of stashing them on the map object.
* "Are you sure?" confirmation if user reverts, changes group, or leaves page.
* Disable controls (save, revert, change group, click blockface) during Ajax requests
* Refactor and simplify `adminTerritoryPage.js`
=> Allow saving updated group territory

src/nyc_trees/sass/partials/_survey.scss
I was able to fix two issues with this. 
The media queries were hiding the map-sidebar on 767px width only.
There was an overflow-x: hidden; which for some reason was disabling all scrolling functionality for y as well.
=> fixed media query and scroll issues for #787 and #788

src/nyc_trees/js/src/map.js
This changes the endpoint of the application basemaps so that they are served by Fastly's (CartoDB's CDN) shared domain SSL URL.
Attempts to resolve #762.
=> Serve basemap over HTTPS

deployment/ansible/roles/nyc-trees.app/templates/nginx-nyc-trees-app.conf.j2, deployment/troposphere/app_template.py, src/nyc_trees/apps/home/urls.py, src/nyc_trees/nyc_trees/settings/base.py, src/nyc_trees/requirements/base.txt
This changeset wires up [Watchman](http://django-watchman.readthedocs.org/en/latest/index.html) to the `/health-check/` application route. Nginx reverse proxies requests to `/health-check/` directly to it, bypassing HTTPS redirects. The application Elastic Load Balancer (ELB) is also setup to use this new endpoint.
In addition, the default Watchman route was also added to `SOFT_LAUNCH_REGEXES` so that it can bypass feature flags.
First pass at resolving #232.
=> Setup Watchman framework for application health check endpoint

deployment/MIGRATIONS.md, scripts/aws/setupdb.sh, src/nyc_trees/apps/home/management/commands/set_django_site_domain.py
This change adds support for setting the `name` and `domain` of the default site in `django_site`. Support has been added via `setupdb.sh`, which depends on the existence of a Django management command called `set_django_site_domain`.
If no name or domain is passed to `setupdb.sh` or the Django management command, then it defaults to `treescount.nycgovparks.org`.
A codified solution to https://github.com/azavea/nyc-trees/issues/393.
=> Add support for setting Django site domain

README.md
Includes an update to README.md explaining the data processing steps.
To test, wipe and reload your survey data with ``./scripts/manage.sh reload_dev_data`` then verify that the Bronx blockfaces are now visible on the progress map.
=> Add Bronx data to blockface fixture

deployment/ansible/roles.txt
See also: https://github.com/azavea/ansible-kibana/pull/5
=> Bump default version of Kibana to 4.0.1

src/nyc_trees/apps/event/event_list.py, src/nyc_trees/apps/event/views.py, src/nyc_trees/apps/survey/templates/survey/partials/progress_page_blockface_popup.html, src/nyc_trees/apps/survey/views.py, src/nyc_trees/apps/users/views/group.py, src/tiler/sql/user_reservable.sql
- Hides inactive groups from the group listing page
- Hides inactive group's events from the event list
- Only allows group admins access to the group detail for inactive groups
- Makes blockfaces appear unavailable on the progress and reservations
maps unless the user is a trusted mapper or admin of the inactive group
Fixes #741
=> Hide inactive groups from most users

src/nyc_trees/nyc_trees/settings/base.py
This changeset explicitly sets the default file storage backend to the file system. Mostly doing this so that we're careful about how we introduce S3 storage support.
=> Ensure that FileSystemStorage is the default

deployment/ansible/group_vars/development, deployment/troposphere/data_store_template.py
This changeset sets the `log_min_duration_statement` to `500` milliseconds within the PostgreSQL instance on Vagrant and RDS.
=> Set PostgreSQL log_min_duration_statement setting

src/nyc_trees/apps/event/routes.py, src/nyc_trees/apps/event/urls/group.py, src/nyc_trees/apps/event/views.py, src/nyc_trees/js/backend/url2pdf.js, src/nyc_trees/libs/phantomjs.py
To test, browse to an event detail page and append "/printable-map/" to the URL
(e.g. `/group/east-side-mappers/event/map-a-maple/printable-map/`).
Currently as a proof of concept the test endpoint returns a PDF showing the progress page.
That page has some problems (image doesn't fill the page; scrollbar shown),
but those problems go away when rendering a map which fills the entire page.
We will need to design print-oriented views for the maps we want to print.
=> Allow a view to return a PDF version of a webpage

deployment/ansible/roles.txt, deployment/ansible/roles/nyc-trees.common/meta/main.yml
This changeset adds the updated Amazon RDS certificate bundle to all instances so that they can securely communicate with RDS after 23 Mar 2015.
See also: https://forums.aws.amazon.com/ann.jspa?annID=2889
=> Add updated Amazon RDS certificate bundle to all instances

deployment/troposphere/data_store_template.py
This changes the database storage type to SSD (`gp2` for general purpose SSD storage).
Before applying this to staging:
=> Change database storage type to SSD

src/nyc_trees/apps/survey/templates/survey/partials/radios.html, src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html, src/nyc_trees/sass/partials/_buttons.scss
Apparently by adding a width of 100% the pixel gap is removed and the buttons still retain appropriate width. This is expected behavior, but was not working initially when first working through the issue.
=> removed unnecessary classes - fixed 1px gap in btn-groups - fixes #832

deployment/ansible/roles.txt, deployment/ansible/roles/nyc-trees.app/defaults/main.yml, deployment/ansible/roles/nyc-trees.tiler/defaults/main.yml, src/nyc_trees/nyc_trees/settings/base.py, src/nyc_trees/nyc_trees/settings/development.py, src/nyc_trees/nyc_trees/settings/production.py, src/nyc_trees/nyc_trees/settings/test.py, src/nyc_trees/requirements/base.txt, src/tiler/server.js
This changeset adds a Redis backed cache to all environments other than testing. Non-default settings include:
- The Hiredis parser is being used
- Socket timeout is explicitly set to 3
- Connection failure exceptions are suppressed
- The Redis database at index 1 is being used
Attempts to resolve #169.
=> Add support for a Redis backed cache

deployment/ansible/roles/nyc-trees.collectd/templates/df.conf.j2, deployment/ansible/roles/nyc-trees.graphite/templates/df.conf.j2
This changeset removes the `Device` setting from the Collectd plugin because Collectd intelligently collects metrics from all mounted devices automatically.
=> Remove device settings from Collectd df plugin

src/nyc_trees/apps/home/templates/home/training_instructions.html, src/nyc_trees/apps/home/training/views.py, src/nyc_trees/apps/survey/templates/survey/reservations_instructions.html, src/nyc_trees/apps/survey/views.py
This displays the first 2 steps of reservations instructions on the
training instructions page.
Also adds changes from #767 which did not get merged in previously.
Fixes #448
1. Login as a user with no training
2. Click RSVP button on any mapping event
=> Style training instructions page

src/nyc_trees/nyc_trees/settings/base.py, src/nyc_trees/nyc_trees/settings/development.py
This changeset overrides the default Django log settings so that everything funnels through to the console (which ends up going to `/var/log/nyc-trees-app.log`). In development, the log level defaults to `DEBUG`, but `INFO` everywhere else.
=> Send all Django logs to the console

deployment/ansible/group_vars/development, deployment/ansible/roles.txt, deployment/ansible/roles/nyc-trees.app/meta/main.yml, deployment/ansible/roles/nyc-trees.app/tasks/configuration.yml, deployment/ansible/roles/nyc-trees.celery/meta/main.yml, deployment/ansible/roles/nyc-trees.celery/vars/main.yml, scripts/debugcelery.sh, src/nyc_trees/nyc_trees/__init__.py, src/nyc_trees/nyc_trees/celery.py, src/nyc_trees/nyc_trees/settings/base.py
This changeset adds Celery support to the application servers by wiring up a Redis broker and launching a Celery worker on each application server. The workers aren't tied to the application server they colocate with; tasks still flow through a broker that attempts to evenly distribute work.
In addition, Celery signals are configured to emit metrics about job count and duration to Graphite via StatsD/Statsite.
Attempts to resolve #851.
=> Add Celery support to application server

src/nyc_trees/apps/mail/templates/mail/group_mapping_approved.txt, src/nyc_trees/apps/mail/templates/mail/group_mapping_approved_subject.txt, src/nyc_trees/apps/mail/views.py, src/nyc_trees/apps/users/tests.py, src/nyc_trees/apps/users/views/group.py, src/nyc_trees/libs/data.py, src/nyc_trees/nyc_trees/settings/base.py
Individual mappers request access to map in a group's territory. If a group admin approves that request, we notify the user and send a link to the reservation page.
Because we are going to have several message types, some on demand, some scheduled, I opted to put as keep much of the email logic as possible, along with the message templates, in a new "mail" app rather than start scattering them around the application.
Fixes #854
=> Send email when trusted mapper is approved

src/nyc_trees/apps/core/models.py, src/nyc_trees/nyc_trees/settings/base.py, src/nyc_trees/nyc_trees/settings/production.py, src/nyc_trees/requirements/production.txt
The VPC id is pulled from the instance metadata and used as the S3 bucket
name, which ensures that staging and production use different S3 buckets
but have identical settings files.
Since we can set the default file storage separately from the storage used
for static assets (JS, CSS, etc.), I decided to make S3 storage the
default storage mechanism for production.
Fixes #352
=> Use S3 for persistent file storage on production.

src/nyc_trees/apps/core/migrations/0018_auto_20150318_1233.py
Commit fda90cf modified the image field of Group, but neglected to inlude
migrations.
=> Add missing migrations for changed image field

deployment/ansible/roles/nyc-trees.app/templates/logrotate-nyc-trees-app.j2, deployment/ansible/roles/nyc-trees.app/templates/logrotate-nyc-trees-gunicorn.j2
`logrotate` runs daily to rotate the application server logs in a way that causes Gunicorn to think that they've been deleted. In order to resolve this issue, after a rotate occurs, an application server restart is triggered to force Gunicorn to reestablish a handle to the file.
=> Fix Gunicorn lost file handles caused by logrotate

src/nyc_trees/nyc_trees/settings/development.py
Management commands inherit the same logging settings supplied to the Django application. In development, database related logging settings were set to `DEBUG`, which allowed SQL debugging output to leak into management command execution. This change sets the database backends back to log level `INFO`.
=> Fix log level DEBUG messages emitted by management commands

src/nyc_trees/apps/event/views.py, src/nyc_trees/apps/mail/templates/mail/rsvp.txt, src/nyc_trees/apps/mail/templates/mail/rsvp_subject.txt, src/nyc_trees/apps/mail/views.py, src/nyc_trees/apps/users/tests.py
When registering for an event the details are emailed to the user.
The text of the email is draft and subject to change and approval.
Fixes #856
=> Send email on RSVP

src/nyc_trees/templates/admin/base_site.html
This is very useful during development and can only improve the end user
experience. You can use this link to get back to the site, from the admin.
=> Add navlink to main site from admin

deployment/README.md, src/failover_website/index.html
More documentation for the Route 53 DNS failover requirements, and a proposed home for the contents of the static S3 website.
=> Add documentation around DNS failover and static site stub

src/nyc_trees/nyc_trees/settings/base.py
Changing to `noreply@treescount.nycgovparks.org`.
Required to resolve #724.
=> Update default application from e-mail address

src/nyc_trees/apps/core/management/commands/dump_models.py, src/nyc_trees/apps/core/tasks.py, src/nyc_trees/libs/custom_storages.py, src/nyc_trees/nyc_trees/settings/production.py, src/nyc_trees/requirements/base.txt
The command takes an optional argument, which will be the name of the directory, under the default Django storage backend, into which the CSV files will be written.
I wrote the export as a plain function call, but ensured that all the arguments are serializable, so that if the need for async processing arises we can easy switch to celery.
To test, run ``./scripts/manage.sh dump_tables foo`` then verify that the CSV files are dumped to ``/var/www/nyc-trees/media/foo``
Fixes #865
=> Add management command to dump tables to CSVs

deployment/ansible/roles/nyc-trees.app/tasks/dependencies.yml, src/nyc_trees/apps/census_admin/tasks.py, src/nyc_trees/apps/census_admin/trees.sql, src/nyc_trees/apps/core/management/commands/start_daily_celery_task.py, src/nyc_trees/apps/survey/survey_detail.sql, src/nyc_trees/requirements/base.txt
To test, run `./scripts/manage.sh start_daily_celery_task dump_trees` and `./scripts/manage.sh start_daily_celery_task dump_blockfaces` then verify that the shapefiles files are dumped to `/var/www/nyc-trees/media/dump`
This is a preview PR, since it still needs some additional work to ensure the dumps are stored in a secure fashion when storing on S3.
Fixes #864
=> Add celery tasks for dumping tree and blockfaces tables to shapefiles

src/nyc_trees/apps/mail/templates/mail/reservation_reminder.txt, src/nyc_trees/apps/mail/templates/mail/reservation_reminder_subject.txt, src/nyc_trees/apps/mail/views.py, src/nyc_trees/apps/survey/management/commands/send_reminder_emails.py, src/nyc_trees/apps/survey/migrations/0014_blockfacereservation_reminder_sent_at.py, src/nyc_trees/apps/survey/models.py, src/nyc_trees/nyc_trees/settings/base.py
This changeset introduces a management command to be executed via cron
for emailing users about their blockface reservations that will expire
soon. It has a configurable window of time for sending requests and will
keep trying to send notifications once daily for until it succeeds. Can
only be run once daily.
=> Try to send reservation reminder emails daily

src/nyc_trees/apps/census_admin/tasks.py, src/nyc_trees/apps/core/tasks.py
Dev VMs do not have s3 tooling installed. Celery startup was failing because background data dump tasks that make use of the PrivateS3BotoStorage class were trying to import unavailable tools.
=> Delay s3 tool import to prevent dev celery crash

deployment/ansible/roles.txt
See also:
- https://github.com/azavea/ansible-ntp/commit/e22d59a7c405fedbf8a5c8244058b84b0fba9e76
- https://github.com/azavea/ansible-unzip/commit/4dd9a327987d06faabaa31647fcae7ba323e9cf9
=> Bump NTP and Unzip roles to use glob versions

scripts/debugcelery.sh
fixes an issue @jwalgran and I ran into during development where the
script will start more celery workers that don't seem to get jobs if
there is already a celery process in place.
=> Make `debugcelery` stop the correct upstart job

src/nyc_trees/templates/registration/activate.html
This page is shown when activation fails, which most often occurs when clicking the link in the registration confirmation email twice. To cover that case, I also added some copy prompting the person to try to log in.
Fixes #910
=> Fix base template reference in activate.html

src/nyc_trees/apps/login/templates/login/forgot_username.html, src/nyc_trees/templates/registration/activation_email.html, src/nyc_trees/templates/registration/activation_email.txt, src/nyc_trees/templates/registration/password_reset_form.html, src/nyc_trees/templates/registration/registration_complete.html
* Only show sentence with link to census training page when `full_access` enabled
* Also fix spelling of "TreesCount!" in several templates
Fixes #962 
Test using `/admin/waffle/flag/`-- check `full_access` and choose "Disable selected flags for everyone"
=> "Soft launch" version of "register complete" text

src/nyc_trees/apps/survey/admin.py
fixes #963 on github
this adds search and filters as pictured:
It's clear that these filters would be useful, but I'm not sure what we're looking for as far as search fields. Anything that is walkable in standard orm style (ie. `user__username`, as included) is readily available.
@dboyer thoughts?
=> Add search and filters to survey admin

deployment/ansible/roles/nyc-trees.beaver/tasks/main.yml, deployment/ansible/roles/nyc-trees.beaver/templates/celery.conf.j2
These changes wire up log shipping for the Celery logs into Logstash/Kibana.
=> Add log shipping support for Celery

deployment/deployment-helper.sh, deployment/troposphere/data_store_template.py, deployment/troposphere/template_utils.py, deployment/troposphere/tiler_hosted_zone_template.py
The following changes are aimed at aligning the staging and production environments:
- Use private hosted zone IDs vs. private hosted zone names
- Add additional instances types
- Label Route 53 hosted zones with VPC ID
- Remove specific data store names
- Switch VPC availability zones
AWS availability zones names don't translate across accounts, so in this case all we're doing is using the same labels.
=> Align staging and production environments

deployment/deployment-helper.sh
Stack outputs contain the VPC ID, and the VPC ID is needed to filter the Route 53 hosted zones to narrow down the ID.
=> Fix filter on private hosted zone ID

src/nyc_trees/apps/home/templates/home/partials/dashboard.html, src/nyc_trees/apps/home/templates/home/partials/home_public.html
There will be no progress until the full launch, so these numbers will always be zero.
Progress map links were removed in 8b2edea, but we want them to be visible when the site is in full access mode.
=> Hide progress counts in soft launch mode / show map links in full access mode

.gitattributes
This change prevents Git from attempting to alter EOT files in the repository.
=> Treat EOT files as binary

src/nyc_trees/apps/home/templates/home/partials/dashboard.html
The training section is hidden via partial on the user profile page, but
needs a slightly different layout on the logged in home page.
Fixes #1003
=> Hide training on soft launch logged in home page

src/nyc_trees/requirements/base.txt
The Internet suggested this range syntax for safety
https://groups.google.com/forum/#!msg/python-virtualenv/DvG1InRGdR0/14b9CISO2AcJ
=> Pin Django dependency to 1.7.x

src/nyc_trees/apps/core/tasks.py, src/nyc_trees/apps/event/views.py, src/nyc_trees/apps/mail/tasks.py, src/nyc_trees/apps/mail/views.py, src/nyc_trees/apps/users/tests.py
Since the meeting point for an event may not be easily expressed as an
address, it helps to send the registrant a map centered on the event
location.
I made the ``send_to`` helper expect and handle a list of attachments
because reservation confirmation emails will need to include both a
static data collection template and the dynamic reservation map PDF.
Is is possible that the PDF for a new or updated event is has not been
created by the time a person RSVPs for the event, so we need to chain
the notification task after ``wait_for_default_storage_file``.
I tested this with the following method:
1. Start two instances of ``./scripts/debugcelery.sh``
1. Open a browser to an event detail page with an RSVP button
1. Open another browser to the edit page for the same event
1. Edit the location …
=> Attach event PDF to reservation confirmation email

src/nyc_trees/templates/registration/activation_email.html, src/nyc_trees/templates/registration/activation_email.txt
The HTML template had stale footer text.
The text template included a custom footer in addition to inheriting the footer from the base template.
=> Updated and remove dup activation email footers

src/nyc_trees/sass/partials/_header.scss
The white blended in too much with the logo. This provides more contrast.
Before:
After:
=> Change hamburger menu color to grey

src/nyc_trees/apps/census_admin/tasks.py
Prevents the dump task from producing invalid CSVs when a text value contains a comma.
Test by making sure Celery is running and then running the ``dump_db`` command
```
./scripts/manage.py dump_db
```
In dev, the files will be written to ``/var/www/nyc-trees/media/dump``
If you want to test this more than once you will need to delete records from ``core_taskrun``.
Fixes #934
=> Quote values in CSV dumps

src/nyc_trees/apps/home/templates/home/partials/circle.html, src/nyc_trees/apps/home/templates/home/partials/dashboard.html, src/nyc_trees/apps/home/templates/home/partials/home_public.html, src/nyc_trees/apps/home/templates/home/partials/ticker.html, src/nyc_trees/apps/home/tests.py, src/nyc_trees/apps/home/views.py, src/nyc_trees/apps/users/__init__.py, src/nyc_trees/apps/users/templates/users/partials/profile/contributions.html, src/nyc_trees/apps/users/views/user.py, src/nyc_trees/libs/sql.py
* Add tabbed displays for "all time", "past week", and "my trees"
* Show stats in each tab per wireframes
* Augment contexts with new stats
* Continue to show related but simpler "contributions" section on profile page
=> Show more stats on logged in homepage

deployment/packer/template.js
This change adds the Jenkins `GIT_BRANCH` environment variable to Amazon Machine Images after they're built.
=> Add GIT_BRANCH to AMI tags

src/nyc_trees/gulpfile.js, src/nyc_trees/npm-shrinkwrap.json, src/nyc_trees/package.json
Some fixes that seem to make using watchify more stable have landed since
our previous version, but upgrading was not possible because watchify
switched away from polling to inotify for linux hosts, which does not
work in a VirtualBox shared folder.
3.0 added the ability to specify polling for file watching, which lets us
update.
Attempts to fix #712
=> Update watchify to 3.0, and explicitly use polling.

src/nyc_trees/apps/home/templates/home/home.html, src/nyc_trees/apps/home/templates/home/partials/circle.html, src/nyc_trees/apps/home/templates/home/partials/dashboard.html, src/nyc_trees/apps/home/templates/home/partials/home_public.html, src/nyc_trees/apps/home/templates/home/partials/species_modal.html, src/nyc_trees/apps/home/views.py, src/nyc_trees/apps/users/__init__.py, src/nyc_trees/apps/users/templates/users/partials/profile/contributions.html, src/nyc_trees/apps/users/templates/users/profile.html, src/nyc_trees/libs/sql.py, src/nyc_trees/sass/partials/_home.scss
This makes circles clickable on the dashboard, home page, and user
profile.
* Blocks should go to the progress map
* Events should go to the events page
* Users should display a modal with some basic users stats
* Species should display a modal with stats about surveyed species
Fixes #972
=> Make dashboard circles clickable

src/nyc_trees/apps/core/admin.py, src/nyc_trees/apps/core/migrations/0021_auto_20150408_1216.py, src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/survey/templates/survey/progress.html, src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html, src/nyc_trees/apps/survey/views.py, src/nyc_trees/js/src/lib/mapHelp.js, src/nyc_trees/js/src/map.js, src/nyc_trees/js/src/progressPage.js, src/nyc_trees/js/src/reserveBlockfacePage.js, src/nyc_trees/sass/partials/_map.scss
* Add fields to User model to record whether user has seen the help
* Record same information on session object for non-logged-in users
* Help is considered shown after page is loaded for the first time
* Communicate `help_shown` to JS via data attribute on map element
New module `lib/mapHelp.js` controls showing the help
* Show legend modal on page load
* Show notification (once) when legend closed
* Hide notification on any click
To test:
1) Log out
2) Pull down the branch, and build
3) Visit progress page. Help should be shown.
4) Close legend. Notification should be shown.
5) Click anywhere. Notification should disappear.
6) Log in. Help should not be shown.
7) Show and close legend. Navigation should not appear.
8) Visit new reservations page. Help should be shown.
9) Close legend. …
=> Show help on Progress Page and New Reservations page

src/nyc_trees/nyc_trees/settings/production.py
This change allows the application to service requests via the training URL by adding it to Django's `ALLOWED_HOSTS`.
=> Add support for training environment

deployment/troposphere/app_template.py, deployment/troposphere/data_store_template.py, deployment/troposphere/tiler_template.py
These changes adjust the CloudWatch alert thresholds based on alerts we've received from the staging, training, and production environments.
=> Change CloudWatch alert thresholds based on past alerts

src/nyc_trees/apps/home/templates/home/training.html
addresses #576 on github
This commit changes #576 to a design/content issue and hides some incorrect text for the time being.
=> Hide 'you're almost there' when training complete

src/nyc_trees/sass/partials/_legend.scss, src/tiler/style/default.mss, src/tiler/style/progress.mss
Changes on Progress Map:
* "Unmapped" gray lighter when zoomed out and darker when zoomed in; makes it easier to see the green progress from zoomed out and easier to select when zoomed in
* "Mapped" green lines thicker when zoomed out and normal when zoomed in; makes them stand out more from a distance, but easy to click and distinguish when zoomed in
Changes on Reservation Map:
* "Available" uses blue to make it visually distinctive from "Unavailable"
Fixes #1106
=> Modify colors

src/nyc_trees/js/src/lib/SelectableBlockfaceLayer.js, src/nyc_trees/js/src/reserveBlockfacePage.js, src/nyc_trees/js/src/surveyPage.js, src/tiler/server.js, src/tiler/sql/group_territory_admin.sql, src/tiler/sql/group_territory_survey.sql, src/tiler/sql/progress.sql, src/tiler/sql/user_progress.sql, src/tiler/sql/user_reservable.sql, src/tiler/sql/user_reservations.sql
Removing the GeoJSON speeds up grid tile queries by 4x on a dev VM. Fetching the GeoJSON for a feature via an AJAX request when it is clicked takes less than 50ms in dev.
Connects to #1128
=> Remove GeoJSON from UTF grids

src/tiler/server.js
The metatile setting has a dramatic effect on both real world and perceived tile rendering speed. A larger value may be appropriate for a single tile rendering process but a smaller one be appropriate for
multiple tile rendering processes running in a load balanced cluster. Modifying the server to read the metatile count from the environment allows for experimentation and performance tuning without
code modification or redeployment.
=> Expose tiler metatile count as config option

src/nyc_trees/apps/event/templates/event/partials/rsvp.html
Previously, one could not unregister from an event that had reached
maximum capacity, because the RSVP button would become disabled and
read "At Capacity".
This fixes that by updating the RSVP button so that it cannot be disabled for
users that have registered for an event.
Fixes #1045
=> Fix unable to RSVP from event if it is full

src/nyc_trees/apps/survey/templates/survey/printable_reservations_map.html, src/nyc_trees/apps/survey/views.py, src/nyc_trees/apps/users/tests.py.orig, src/nyc_trees/js/src/printableReservationsMapPage.js, src/nyc_trees/libs/sql.py
* Python code creates list of endpoints
* Template stores it in a map data attribute
* JavaScript puts endpoint circle markers in a Leaflet layer
Fixes #904
=> Show block edge endpoints on printable reservations map

src/nyc_trees/apps/event/event_list.py, src/nyc_trees/apps/event/templates/event/event_list_page.html, src/nyc_trees/apps/event/tests.py
Only display events that you have explicitly RSVPd to on the events
listing page.
Test this by RSVPing to an upcoming event that belongs to a group that you are *not* following. The event should appear in "Your events this week".
Fixes #1027
=> Show all RSVPd events on "Your Events this week"

deployment/ansible/roles.txt
This change fixes a scenario during AMI creation where Packer installs the `python-pip` and `python-dev` packages prior to running Ansible because Python is an Ansible dependency. The version of the `python-pip` package installed when no version number is specified (as is the case in the Packer template) conflicts with the version installed by this role because it prompts the user for dependent package downgrades.
See also: https://github.com/azavea/ansible-pip/pull/1
=> Bump pip role version

deployment/ansible/roles/nyc-trees.beaver/templates/windshaft.conf.j2, deployment/ansible/roles/nyc-trees.logstash/templates/logstash.conf.j2, src/tiler/server.js
These changes break individual Windshaft tile requests into specific attributes that are indexed in ElasticSearch for querying.
1. Windshaft emits logs as JSON
2. Beaver picks them up and ships them to Logstash
3. Logstash converts the `timestamp` field into `@timestamp` with the proper formatting
4. Resulting JSON blob is shipped to ElasticSearch
---
=> Add Windshaft request parsing support

deployment/deployment-helper.sh, scripts/aws/promote-ami.sh
These changes support AMI promotion from one account to another. Sharing is facilitated by giving launch permissions to another account ID. Once shared, the AMI tags are updated to reflect the promotion and avoid any image pruning processes.
=> Codify AMI promotion process

src/nyc_trees/apps/core/admin.py, src/nyc_trees/apps/event/admin.py, src/nyc_trees/apps/survey/migrations/0017_auto_20150415_1419.py, src/nyc_trees/apps/survey/models.py
Adds the ability to edit an event location from the admin site
Disables access to to the builtin Group model that we don't use
In staging/production builds:
Disables editing Site objects, which we set up with a script
Disables editing a few Waffle models, but leaves Flag enabled
Also fixes #1065
=> Clean up the Django Admin page

src/nyc_trees/apps/home/templates/flatpages/training.html
This should fix the issue where buttons touch bottom of page/area on tablet.
=> Add space on training navigation buttons. Fixes #1137

src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/login/forms.py, src/nyc_trees/apps/users/urls/user.py
Add form validation error to prevent registration of usernames that
would conflict with any of our special `/user/*` URLs.
Fixes #1171
=> Prevent registration of usernames that conflict with URLs

src/nyc_trees/apps/core/templates/core/partials/email_form.html, src/nyc_trees/apps/core/templates/core/partials/non_field_errors.html, src/nyc_trees/apps/event/templates/event/partials/event_form.html, src/nyc_trees/apps/login/templates/login/forgot_username.html, src/nyc_trees/apps/users/templates/groups/settings.html, src/nyc_trees/templates/registration/activation_complete.html, src/nyc_trees/templates/registration/login.html, src/nyc_trees/templates/registration/password_change_form.html, src/nyc_trees/templates/registration/password_reset_confirm.html, src/nyc_trees/templates/registration/password_reset_form.html, src/nyc_trees/templates/registration/registration_form.html
This partial will allow us to more easily customize the style of form
errors that are not specific to any particular field.
Fixes #1023
=> Add partial for non_field_errors

src/nyc_trees/apps/event/templates/event/email_rsvps.html, src/nyc_trees/apps/home/templates/home/partials/legend.html, src/nyc_trees/apps/survey/templates/survey/partials/progress_legend.html, src/nyc_trees/apps/survey/views.py, src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/js/src/progressPage.js
Modifies progress page to change legend text on mode change, while showing
default legend text before the mode is changed.
Fixes #957
=> Replace lorem ipsum on progress map, group detail, and event email form

src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/sass/partials/_globals.scss, src/nyc_trees/sass/partials/_home.scss
I removed the data about number of attendees because I felt like the number of followers, which we already show on this page, is a better representation of that activity. Plus, this allows us to use the standard 3 circle pattern that is on the dashboard.
=> Add progress circles to group page. Fixes #1100

src/nyc_trees/apps/core/templates/core/partials/polling_download_section.html
Was falling off the page like this:
Now it's looking sharp like this:
=> Fix sizing on download button

src/nyc_trees/apps/users/templates/groups/detail.html
I accidentally removed the correct variable ```counts.tree``` with the integer ```3``` in #1155. Did not mean to do that.
=> Replace variable

src/nyc_trees/sass/partials/_globals.scss
I noticed this glitch when testing the map pages on iOS 8. The page height was expanding beyond the height of the screen, making the page scrollable, which we don't want.
Before video:
http://sandbox.azavea.com/temporary/nyc-ios8-scroll-before.mov
After video:
http://sandbox.azavea.com/temporary/nyc-ios8-scroll-after.mov
=> Fix ios8 scrolling glitch on map page

src/nyc_trees/apps/survey/views.py
The `_validate_event_and_group` function returns an HTTP error if the
user is not checked into the current event. Consumers of this helper function
erroneously assume that a valid event is returned. The result is that some
survey endpoints can be triggered by users even if they have not been
checked into the event.
=> Don't ignore event related HTTP errors on survey pages

src/nyc_trees/apps/home/templates/home/partials/dashboard.html, src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/sass/partials/_home.scss
Reduce padding between circles on mobile and reduce margin on left and right of container. Fixes #1213.
=> Fix circle size on mobile

src/nyc_trees/sass/partials/_footer.scss, src/nyc_trees/sass/partials/_globals.scss, src/nyc_trees/sass/partials/_header.scss, src/nyc_trees/sass/partials/_survey.scss, src/nyc_trees/sass/partials/_variables.scss
This fixes a glitch with the default browser on Android 4.2 and earlier that caused elements with ```position: fixed``` and ```transform: translate``` to not register the transform.
Here is a stackoverflow discussion about the glitch. http://stackoverflow.com/questions/18572488/transform-doesnt-work-on-position-fixed-divs-on-android
Using ```transform: translate``` to reposition elements—in our case, the side navigation and header when the navigation opens—is generally more performant than alternatives like ```left``` or ```margin-left```. However, in this case, I've switched to ```left```, which works on Android 4.2 and earlier.
I've tested the basic page and map page layouts on latest Chrome, latest Firefox, IE9, Android 4.0, iOS7, and iOS8. All check out. More testing to come.
=> Fix glitch on Android 4.2 and earlier

src/nyc_trees/js/src/trainingFlatpage.js
fixes #1194 on github
tested on chrome, chrome iphone5 emulation, and firefox.
=> Scroll to top during training subpage navigation

src/nyc_trees/apps/core/admin.py, src/nyc_trees/apps/event/admin.py, src/nyc_trees/nyc_trees/settings/base.py
The Django admin has a built in slippy map for editing geometries, built
on top of OpenLayers. By default, the admin template loads OpenLayers
from http://openlayers.org/api/2.13/OpenLayers.js, which fails with an
"insecure" error when the site is running under https.
This commit overrides that insecure URL with a secure one from cdnjs.
Connects to #952
=> Load admin page OpenLayers from https CDN

src/nyc_trees/apps/event/templates/event/printable_event_map.html, src/nyc_trees/apps/survey/templates/survey/printable_reservations_map.html, src/nyc_trees/sass/partials/_map.scss
Header text added. Styling welcome.
In particular, the `map-pdf-header` style specifies `background: white`.
That works correctly when viewing the printable map as HTML (e.g. `/blockedge/printable-map`)
but does not work when rendered to a PDF by PhantomJS.
Fixes #880
=> Add header text to printable maps

src/nyc_trees/apps/event/views.py, src/nyc_trees/apps/survey/layer_context.py, src/nyc_trees/apps/survey/views.py, src/nyc_trees/apps/users/views/group.py, src/nyc_trees/js/src/lib/BlockfaceLayer.js, src/nyc_trees/js/src/progressPage.js, src/tiler/server.js, src/tiler/sql/group_progress.sql, src/tiler/sql/progress.sql, src/tiler/sql/user_progress.sql, src/tiler/style/progress.mss
- Simplifies layers by moving computing of `survey_type` to the app server.
- Enables caching of the main progress layer by removing the `user` query parameter
- Simplifies styling of the various progress layers by generating a `is_mapped` column in the SQL query
- Changes group progress layer to show mapped vs. unmapped blockfaces
- Adds support for clicking blockfaces to see information to the group mode
Fixes #1212 
Fixes #1220
=> Cleanup progress modes

src/nyc_trees/apps/users/tests.py
Layout changes have now reduced the number of privacy links that appear on the page.
=> Fix privacy button visibility unit test

src/nyc_trees/apps/event/templates/event/partials/event_popup.html, src/nyc_trees/apps/event/templates/event/partials/event_section.html, src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html, src/nyc_trees/apps/users/templates/groups/partials/event_section.html, src/nyc_trees/apps/users/templates/users/partials/event_email_opt_in.html, src/nyc_trees/sass/partials/_globals.scss, src/nyc_trees/sass/partials/_header.scss, src/nyc_trees/sass/partials/_map.scss, src/nyc_trees/sass/partials/_survey.scss, src/nyc_trees/sass/partials/_variables.scss
Fixes #1239 and fixes #1241.
Adds media queries around height. Shrinks headers and actionbar on shorter devices.
=> Add style for low height device

src/nyc_trees/sass/partials/_map.scss
Address but does not fix the issue #721.
Removes the border on the action-bar when it's empty. Slightly better on desktop, but doesn't impact mobile.
Before:
After:
=> Make actionbar invisible when empty

src/nyc_trees/apps/event/event_list.py
=> On events page, swap order of training and mapping tabs

deployment/deployment-helper.sh, deployment/troposphere/tiler_hosted_zone_template.py
This changeset aims to avoid CloudFront distribution origin changes by using a public DNS record for the tiler (tiles.treescount.foo.com). The private DNS record used by the application server to discover the tile server remains untouched. In addition, the CloudFront distribution endpoint (with HTTPS) will continue to be used to serve tiles because we only have an SSL certificate for the root domain.
=> Bypass CloudFront origin swap; use public tiler DNS record

src/nyc_trees/apps/event/views.py
=> Add https:// prefix to event feed link urls

jmeter/my-blockedge-progress.jmx
This changeset adds a JMeter test plan for the My Blockedge Progress drop down on the progress map. This test plan is very similar to the All Users Blockedge Progress test plan, except that it includes a Random Variable for user ID. This user ID is appended to request paths as a query string: `?user=${RANDOM_USER_ID}`.
The random user ID is per thread, so if you try to simulate 10 users (the default), each will carry its random user ID until all requests are processed.
=> Add JMeter test plan for My Blockedge Progress

src/nyc_trees/apps/core/migrations/0025_group_territory_updated_at.py, src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/survey/layer_context.py, src/nyc_trees/apps/users/views/group.py
Add `group.territory_updated_at` field and use for territory cache buster
Ensures that the cache buster is updated when blockfaces are unassigned
from a group's territory without any other changes taking place.
To test, remove a blockface from a group's territory and save without
making any other changes.  The color of the removed blockface should
change to indicate that it is now unavailable.
Fixes #791
=> Add group.territory_updated_at field and use for territory cache buster

src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/login/forms.py, src/nyc_trees/apps/login/routes.py, src/nyc_trees/apps/login/templates/login/activated.html, src/nyc_trees/apps/login/templates/login/activation_email_sent.html, src/nyc_trees/apps/login/templates/login/partials/inactive_validation_message.html, src/nyc_trees/apps/login/templates/login/send_activation_email.html, src/nyc_trees/apps/login/urls/accounts.py, src/nyc_trees/apps/login/urls/login.py, src/nyc_trees/apps/login/views.py
If a person has registered, but not activated their account, and they attempt to log in, we want to tell them why we can't yet log them in, and provide them a way to request another activation email.
This commit adds a workflow, similar to "forgot username," for resending activation emails. There are a few key differences.
* If the account is already active, there is no token, so we cannot
send an email and, instead, prompt the person to log in.
* Adding an anchor tag to the inactive account validation message
requires overriding the authentication form, so that the HTML
content can be marked as "safe."
Test by registering a new account, and then attempting to log in before activation.
Fixes #647
=> Add activation email resend workflow

src/nyc_trees/apps/home/routes.py, src/nyc_trees/apps/home/templates/home/individual_mapper_instructions.html, src/nyc_trees/apps/home/templates/home/trusted_mapper_request_sent.html, src/nyc_trees/apps/home/urls.py, src/nyc_trees/apps/home/views.py, src/nyc_trees/apps/survey/routes.py, src/nyc_trees/apps/survey/views.py, src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/apps/users/tests.py, src/nyc_trees/apps/users/urls/group.py, src/nyc_trees/apps/users/views/group.py, src/nyc_trees/js/src/group_detail.js
When non individual mappers try to access the Reservations page, they
will be redirected to the reservations instructions page.
Fixes #1198
=> Redirect non-mappers to Reservations Instructions page

src/nyc_trees/apps/home/templates/home/partials/dashboard.html
This commit changes the heading and copy of the training section and moves it to the top of the dashboard, so it is the first thing a new user sees when logging in.
First login:
After some training:
Training complete:
Fixes #1275
=> Move training to top of the dash

src/nyc_trees/sass/partials/_home.scss
=> removed margin-left on footer logo - fixes #1336

src/nyc_trees/js/src/map.js
=> Prevent scrolls being swallowed up by leaflet on Chrome for Android

src/nyc_trees/apps/core/templates/core/partials/nav.html, src/nyc_trees/apps/home/templates/home/individual_mapper_instructions.html, src/nyc_trees/apps/survey/routes.py, src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/apps/survey/urls/survey.py, src/nyc_trees/apps/survey/views.py
Redirects to the appropriate page based on the users training / individual
mapper status, # of reservations, and whether an event is in progress.
Lots of thanks to @RickMohr!
Fixes #1252
=> Add link to treecorder in main navigation

src/nyc_trees/apps/home/templates/home/partials/training.html
The estimates were removed from the other tasks on the training checklist, but this entry was mistakenly omitted.
Fixes #1361
=> Remove time estimate from follow groups task

deployment/deployment-helper.sh, deployment/troposphere/tiler_hosted_zone_template.py
This changeset adds CloudWatch alarms to CloudFront tile distribution. The two metrics right now are backend 4XX and 5XX failures.
=> Add CloudWatch alarms to CloudFront distribution

src/nyc_trees/apps/home/templates/home/partials/circle.html
Changed the order of `if` clauses to prevent capturing incorrect `url` in context
Fixes #1375
=> Fix "species" progress circle on profile page

src/nyc_trees/apps/event/views.py
They are hidden on the list view and should also be hidden on the map.
Fixes #1379
=> Hide private events on the map page

src/nyc_trees/apps/mail/templates/mail/group_mapping_approved_subject.txt, src/nyc_trees/apps/mail/templates/mail/rsvp_subject.txt
By default Django's template engine escapes template content to protects against injection. When we are using a template to render a plain text email subject, we do not want this escaping.
Fixes #1401
=> Don't escape punctuation in email subject lines

src/nyc_trees/apps/home/templates/home/quiz_complete_page.html, src/nyc_trees/apps/home/templates/home/quiz_page.html, src/nyc_trees/apps/home/training/views.py, src/nyc_trees/js/src/lib/states.js, src/nyc_trees/js/src/quizCompletePage.js, src/nyc_trees/js/src/quizPage.js
Fixes the issue where multiple users of the same device (library, classroom, etc.) see the first user's quiz status and/or results.
Fixes #1399
=> Store quiz state per user

src/nyc_trees/apps/survey/views.py
If a group has a border polygon defined, we can show it on the group map even if the territory for the group has not been defined.
Fixes #1407
=> Show group border even if territory is not defined

src/nyc_trees/sass/partials/_globals.scss
=> Remove outline on tab click on Firefox

jmeter/all-users-3x-zoom-blockedge-progress.jmx
This changeset adds a JMeter test plan for the All Blockedge Progress map with steps for zooming in 3x. So, first the initial map loads, then zoom in 3x total, waiting each time for all the blocks to load.
---
On a development virtual machine:
=> Add JMeter test plan for All Blockedge Progress with 3x zoom

src/nyc_trees/apps/survey/templates/survey/partials/group_popup.html, src/nyc_trees/sass/partials/_map.scss
=> Fix long group names in actionbar

deployment/troposphere/template_utils.py
This changeset allows application and tiler instances to be launched as C3 and C4 class instance types.
=> Add support for C3 and C4 class instance types

src/nyc_trees/apps/core/migrations/0027_auto_20150428_1529.py, src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/survey/models.py, src/nyc_trees/libs/mixins.py
It's unclear to me why Django won't pick up the changes to fields other than `Group.territory_updated_at` when I run `makemigrations`.  Since they do not reflect DB changes,
I am not overly worried about it.
Fixes #1413
=> Prevent editing index fields via the Django admin site.

src/nyc_trees/js/src/progressPage.js
The survey, event list, and reservations maps all show content in the
action bar on page load, so I did not do this on those pages.
Fixes #721
=> Add a class to the body when content is added to the actionbar.

src/nyc_trees/gulpfile.js, src/nyc_trees/npm-shrinkwrap.json, src/nyc_trees/package.json
- Update gulp-ruby-sass to 1.0.5 to fix sourcemap and minification support.
- Use autoprefixer to add vendor prefixes to CSS selectors and properties.
Sourcemaps were broken in the version of gulp-ruby-sass we were using
because it wanted us to serve the original files and would not allow us
to choose the path to serve them from.
Minification was not implemented in favor of using a "compressed"
outputStyle because we did not have sourcemap support and I wanted to
enable debugging production issues easily.
Minification doesn't get us much (33Kb uncompressed vs. 30Kb compressed),
but it was trivial to add.
I chose to use '>1% in US' as the browsers to support with autoprefixer, though it is trivial
to tweak this if we need to.
Bringing in the latest autoprefixer also required updating …
=> Update gulp-ruby-sass and add autoprefixer

src/nyc_trees/apps/core/templates/base.html, src/nyc_trees/apps/core/templates/core/partials/nav.html, src/nyc_trees/apps/core/templates/skeleton.html, src/nyc_trees/apps/event/templates/event/event_detail.html, src/nyc_trees/apps/event/templates/event/partials/teammates.html, src/nyc_trees/apps/home/templates/home/partials/home_public.html, src/nyc_trees/apps/home/templates/home/partials/legend.html, src/nyc_trees/apps/home/templates/home/partials/species_modal.html, src/nyc_trees/apps/home/templates/home/partials/training.html, src/nyc_trees/apps/home/templates/home/quiz_page.html, src/nyc_trees/apps/survey/templates/survey/partials/map_another_popup.html, src/nyc_trees/apps/survey/templates/survey/partials/radios.html, src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html, src/nyc_trees/apps/survey/templates/survey/progress.html, src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/apps/users/templates/groups/list.html, src/nyc_trees/apps/users/templates/groups/partials/event_section.html, src/nyc_trees/apps/users/templates/users/partials/achievement.html, src/nyc_trees/apps/users/templates/users/partials/profile/section.html, src/nyc_trees/sass/partials/_globals.scss, src/nyc_trees/sass/partials/_survey.scss, src/nyc_trees/templates/registration/login.html, src/nyc_trees/templates/registration/password_change_form.html, src/nyc_trees/templates/registration/password_reset_confirm.html, src/nyc_trees/templates/registration/password_reset_form.html, src/nyc_trees/templates/registration/registration_form.html
Various changes to produce W3C valid markup.
This only fixes errors, not warnings, and does not alter any flatpages
markup.
Summary of changes:
* Add alt attribute to images
* Add form actions
* Fix invalid element nesting (block level elems inside inline elems)
* Fix stray script tags (declare scripts inside body)
* Fix stray closing tags
Fixes #1415
=> Cleanup HTML

src/nyc_trees/sass/partials/_globals.scss
Git blame makes me think this brace was a victim of a funky merge commit.
Fixes #1499
=> Add missing brace to _globals.scss

src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html, src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/js/src/surveyPage.js
The button will only be present on the last tree, and only if there is
more than one tree form.
If any data has been entered for the tree, a modal  window will be
presented asking for confirmation.
Fixes #954
=> Add ability to delete the last tree in the treecorder.

src/nyc_trees/apps/survey/routes.py, src/nyc_trees/apps/survey/urls/blockface.py, src/nyc_trees/apps/survey/views.py, src/nyc_trees/js/src/lib/SelectableBlockfaceLayer.js, src/nyc_trees/js/src/lib/mapUtil.js, src/nyc_trees/js/src/progressPage.js
It is expensive to render UTF grids for the entire city. This commit removes the grid layer from the progress page, and keeps the click-to-select functionality by adding an endpoint that fetches the feature closest to a point.
Connects to #1492
=> Remove progress UTF grid, add fetch by lat/lng

scripts/aws/setupdb.sh
Now that this app is live, there's not ever going to be a case where we
want to load training pages from version control without a one-off
manual review. This line could now only hurt us.
=> Stop modifying training pages during setup

src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html, src/nyc_trees/apps/survey/templates/survey/survey.html
Sets a max of 100,000 ft for distance and 2,000 in for diam/circumference,
which seems large enough for even the largest blockfaces/trees.
Fixes #1236
=> Add max attribute to treecorder input fields.

src/nyc_trees/apps/survey/templates/survey/blockface_cart.html, src/nyc_trees/apps/survey/templates/survey/reserve_blockface_confirmation.html, src/nyc_trees/apps/survey/tests.py, src/nyc_trees/apps/survey/views.py
* Pages now make sense if you cancel blocks without reserving any
* Language now reflects **new** rather than **all** reservations
* Make language consistent for 1 vs. more than one block
* Refer to "block edges" instead of "blocks"
Fixes #1265
=> Update language in reservation confirmation screens

src/nyc_trees/apps/core/templates/skeleton.html
The ! in the page title results in "TreesCoun..." as the default iOS home screen short cut label. Adding this meta tag provides a default that fits in the allowable home screen icon label space.
Before
After
=> Set an appropriately sized iOS shortcut title

src/nyc_trees/apps/survey/templates/survey/progress.html, src/nyc_trees/js/src/adminTerritoryPage.js, src/nyc_trees/js/src/map.js, src/nyc_trees/js/src/progressPage.js
Fixes #1491 
Fixes #1494
These map pages were generating spurious tiler requests (fixed by this PR):
* Progress - My Progress
* Progress - Groups
These were fine:
* Group Detail
* Event PDF
* Reservations
* Reservations PDF
* Treecorder
* Admin Territory
=> Avoid unnecessary tiler requests

src/nyc_trees/sass/partials/_map.scss
Fixes #1522. The zoom buttons on mobile are not needed because users pinch to zoom. Nobody in user testing clicked on the zoom buttons to zoom. By having fewer buttons, we can better emphasize the geolocate and search buttons.
=> Remove zoom buttons on mobile

src/nyc_trees/apps/event/views.py
This change adds the `includes_training` field to the event feed and
also adds the ablilty to filter the feed by adding querystring arguments.
To show training events:
/event/feed/?includes_training=True
To show mapping events:
/event/feed/?includes_training=False
To show all events (omit querystring):
/event/feed/
You can only filter by the includes_training field for now.
Connects #1457
=> Add includes_training field to event feed

src/nyc_trees/js/shim/select2.js
There is a known bug with the 3.x version of Select2 that causes the
dropdown menu to sometimes immediately close after opening:
https://github.com/select2/select2/issues/2300
https://github.com/select2/select2/issues/2061
This only seems to occur on firefox for Android and the default Android
browser.
It seems to have been fixed in the 4.0 version of Select2, which was
released 2 days ago, but there are a number of breaking changes, so I'm
wary of upgrading to it.
Instead, I'm bringing in a fix I found in a fork of of the library, which
seems to fix the issue without causing any other effects.
Connects to #885
=> Patch the select2 library to fix a bug on some Android browsers

src/nyc_trees/apps/users/templates/users/partials/profile/reservations.html
Fixes #1523. Now help text is displayed under reservations when there are no active reservations.
=> Add conditional for no reservations on dashboard

src/nyc_trees/js/src/lib/SelectableBlockfaceLayer.js, src/tiler/sql/user_reservable.sql, src/tiler/sql/user_reservations.sql, src/tiler/style/default.mss
This fix ensures that blocks do not appear as available on the
reservations page after they have been surveyed.
Connects #1247
=> Fix styling on surveyed blocks

deployment/ansible/roles/nyc-trees.app/meta/main.yml, deployment/ansible/services.yml
We have been seeing out-of-memory issues on the redis server when handling
DB requests, and on the app server when building the production bundle
with `npm run build`.
Adding a swapfile should fix both issues.
Fixes #1555
=> Add swapfiles to both services and app VMs

src/nyc_trees/apps/event/urls/group.py, src/nyc_trees/apps/users/urls/group.py, src/nyc_trees/apps/users/urls/user.py
I used the same regex that Django uses when validating usernames:
https://github.com/django/django/blob/1.7.8/django/contrib/auth/models.py#L371
so I think this should cover all possible usernames
Connects to #1440
Connects to #1443
=> Change URLs to accept all valid usernames

src/nyc_trees/apps/core/migrations/0030_auto_20150506_1635.py, src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/event/migrations/0014_auto_20150506_1634.py, src/nyc_trees/apps/event/models.py
Creating an event or group with a name greater than 50 characters would
fail, because the automatically generated slugs were longer than the
default max_length.
Connects to #1524
=> Increase max slug length to match connected fields.

src/tiler/sql/group_territory.sql, src/tiler/sql/group_territory_admin.sql, src/tiler/sql/group_territory_survey.sql, src/tiler/sql/user_reservations_print.sql
Styling based on the restriction column was added in 3b1bebf6, but
windshaft bombs out if a property referenced in CartoCSS is not in the
SQL query.
Adding the constant ``'none' as restriction`` to these queries will fix
the issue.
Connects to #1572
=> Fix tile generation several maps.

src/nyc_trees/apps/home/templates/home/partials/legend.html, src/nyc_trees/js/src/reserveBlockfacePage.js
Also fixes a problem where auto-panning was happening in "mobile" view when you selected a blockface even though no popup was shown.
Connects #1349
=> When showing blockface popup, auto-pan map to avoid sidebar

src/nyc_trees/apps/core/test_utils.py, src/nyc_trees/apps/survey/migrations/0021_auto_20150506_1406.py, src/nyc_trees/apps/survey/models.py, src/nyc_trees/apps/survey/views.py
These tables are queried to find the most recent update time when
computing tiler cache buster values, when loading that map page.
Survey is queried for the most recent 'updated_at' for every progress page
layer, and BlockfaceReservation.updated_at is queried for every other
map layer.
I am only adding indexes for these 2 table's 'updated_at' columns because
I expect that the number of rows in the other tables we use to calculate
cache busters will remain small, or already have indexes.
I attempted to measure the performance impact of these changes, but the
Postgresql query plan did not use the new indexes.  I suspect this is
because the amount of data in my development DB is rather small.
That said, I expect we will have a large number of rows in these tables
by the end of the census, …
=> Add indexes to 'updated_at' for Survey and BlockfaceReservation

src/nyc_trees/apps/home/training/types.py
I was able to reproduce this in development.
before:
after:
------------------------------------------
connects to #1589 on github
As discussed in person, this is the result of some code assuming an
anonymous user is a logged in user. This commit forces realization
of the user and returns None for the id. The solutions was inspired by
this stackoverflow page:
http://stackoverflow.com/questions/17623234/django-simplelazyobject
This is in response to a bug that turned up on production. Fortunately
the only time this bug would turn up is with a case in which a 404
appropriate. This fix makes sure that a 404 is returned.
=> Fix anonymous user exception on training page

scripts/aws/setupdb.sh
For a few reasons
- The database for every stack already contains these blocks, and they
will not be changing over the course of census. We will only be
getting additions.
- The block rows have a mutable ``is_available`` column used for
tracking the status of the row, and we do not want to overwrite it.
- It slows down the deploy process.
Connects to #1591
=> Remove loading blockfaces from setupdb.sh

src/nyc_trees/js/src/map.js, src/nyc_trees/js/src/progressPage.js
This fixes a race condition where the map `zoomend` event would not fire the
first time a user selects "My Progress" on the Progress map page.
I solved this by replacing the zooming event handlers with a promise.
Connects #1581
=> Fix "My Progress" map tiles not appearing the first time

src/nyc_trees/apps/event/views.py
The `from_email` argument should not be a list.
To test, send an email to event registrants and inspect the console output:
Right:
Wrong:
Connects #1519
=> Fix 500 error when emailing event registrants

src/nyc_trees/apps/core/templates/base.html, src/nyc_trees/apps/core/templates/core/partials/nav.html, src/nyc_trees/apps/event/models.py, src/nyc_trees/apps/home/templates/home/partials/treecorder_modal.html, src/nyc_trees/apps/home/views.py, src/nyc_trees/apps/survey/layer_context.py, src/nyc_trees/apps/survey/routes.py, src/nyc_trees/apps/survey/urls/survey.py, src/nyc_trees/apps/survey/views.py, src/nyc_trees/nyc_trees/context_processors.py, src/nyc_trees/nyc_trees/settings/base.py, src/nyc_trees/sass/partials/_header.scss
- Refactors treecorder link to show a modal when there is ambiguity about how to survey
- Allows mapping events until midnight the day of the event, if the user was checked in to that event
Connects to #150
=> Allow mapping at events all day

src/nyc_trees/js/src/surveyPage.js
This fixes the issue with collapsing a section when its sticky title was at the bottom of the section.
=> Update sticky titles after collapse/expand animation completes

src/nyc_trees/apps/mail/templates/mail/base_email.txt
The content of a plain text email never needs to be escaped. The Django docs explain that autoescape settings are passed from parent to child templates.
https://docs.djangoproject.com/en/1.7/topics/templates/#for-template-blocks
Connects to #1565
=> Disable autoescape in base text email template

deployment/troposphere/tiler_template.py, src/tiler/healthCheck.js, src/tiler/server.js
We want to be able to detect connectivity issues between the tiler and the two services it depends on, the Postgres database and the Redis cache. This commit adds a ``/health-check`` endpoint that attempts to connected to both services and returns the status of those connections in a JSON response.
Test by stopping the Postgres and Redis services and verifying that ``/health-check`` returns an appropriate message.  You can also hack the code or set ``NYC_TREES_TILER_HEALTH_TIMEOUT=1`` to test the timeout functionality. 
Connects to #1129
=> Add a health check endpoint to the tiler

src/nyc_trees/apps/core/templates/500.html
This changeset adds a custom 500 error page template to override the default.
=> Add a custom 500 error page template

src/nyc_trees/apps/event/templates/event/admin_checkin.html, src/nyc_trees/apps/event/views.py
This also sorts the users on the event admin check-in page so that
ambassadors are at the top of the list.
Connects #1530
=> Show ambassador status on event admin check-in page

scripts/aws/setupdb.sh
This changeset makes all of the `loaddata` management command calls consistent.
Successful command output:
```
ubuntu@ip-10-0-3-192:~$ DJANGO_SITE_DOMAIN="treescount.foo.com" /opt/nyc-trees/scripts/aws/setupdb.sh
...
+ envdir /etc/nyc-trees.d/env /opt/app/manage.py loaddata /opt/app/apps/survey/fixtures/borough.json
Installed 5 object(s) from 1 fixture(s)
+ envdir /etc/nyc-trees.d/env /opt/app/manage.py loaddata /opt/app/apps/survey/fixtures/neighborhoodtabulationarea.json
Installed 195 object(s) from 1 fixture(s)
+ envdir /etc/nyc-trees.d/env /opt/app/manage.py assign_block_regions
+ envdir /etc/nyc-trees.d/env /opt/app/manage.py loaddata /opt/app/apps/survey/fixtures/species.json
Installed 132 object(s) from 1 fixture(s)
...
```
=> Make Django loaddata management command references consistent

deployment/ansible/roles/nyc-trees.tiler/defaults/main.yml, src/tiler/healthCheck.js, src/tiler/server.js
In EC2, the RDS user and database name do not match. These changes pass through the backend database name so that the health check can make use of it.
Connects #1129
=> Fix tiler health check by threading through database name

src/nyc_trees/nyc_trees/middleware.py, src/nyc_trees/nyc_trees/settings/base.py
Check if user is banned before processing any views. If they *are*
banned, immediately logout user.
How to test:
1. Login as any user
2. Set `is_banned` to True for that user
3. Refresh the page
4. You be logged out now, and unable to login until the ban is lifted
Connects #1530
=> Restrict access from banned users

src/nyc_trees/apps/survey/templates/survey/partials/progress_legend.html, src/nyc_trees/sass/partials/_legend.scss, src/tiler/style/progress.mss
Parks requested a ramp that ran through the green used throughout the site.
I also tweaked the appearance of the legend a bit. Pushing the labels out to the edges more strongly associates them with the colors that represent those values. Not drawing borders between the color cells just looks nicer to me.
To take this screenshot I adjusted the color breaks in the tiler to demonstrate more variation.
Connects to #1635
=> Update progress color ramp

src/nyc_trees/apps/home/templates/home/trusted_mapper_request_sent.html, src/nyc_trees/apps/users/routes/group.py
If you click 'request independent mapper status" for a group when logged out, after logging in you will be redirected to the group detail page where you can click the button again.
Connects #1666
=> Allow requesting group independent mapper status when logged out

src/nyc_trees/sass/partials/_survey.scss
Remove unneeded padding from actionbar on survey/treecorder. This will fix vertical centering on older iPhones. Fixes #1662.
=> Fix survey centering on iOS

src/nyc_trees/sass/partials/_globals.scss, src/nyc_trees/sass/partials/_home.scss
Some of the modal styles were being overridden. Removing these overrides and removing the overflow property from the html element fixes the issue. Fixes #1661.
=> Fix species modal

src/nyc_trees/apps/survey/checks.py, src/nyc_trees/apps/survey/management/commands/send_reminder_emails.py, src/nyc_trees/nyc_trees/settings/base.py
This adds a new section to the watchman health check to report the
status of cron jobs.
For the send_reminder_emails cron job we report OK if the job has run
at least once in the past 48 hours.
Connects #906
=> Add watchman health check for send_reminder_emails cron job

src/nyc_trees/apps/event/templates/event/email_rsvps.html
An event may have at least 1 RSVP, but those RSVPs may not have opted in to event e-mail notifications.
Connects #1678
=> Clarify event e-mail message when no RSVPs have opted in

src/nyc_trees/apps/census_admin/trees.sql, src/nyc_trees/apps/survey/survey_detail.sql
The state plane projection more closely matches real-world measurements from surveyors.
Here are the results comparing utm18n (coming out of _st_bestsrid) and state plane:
```
tree_id | survey_id | block_id | dist_requested | dist_utm18n | dist_stateplane 
---------+-----------+----------+----------------+-------------+-----------------
528 |       165 |   343906 |         172.50 |      192.95 |          172.52
529 |       165 |   343906 |          35.30 |       39.48 |           35.30
530 |       165 |   343906 |          32.10 |       35.90 |           32.10
531 |       165 |   343906 |          31.50 |       35.23 |           31.50
532 |       165 |   343906 |          31.90 |       35.68 |           31.90
533 |       165 |   343906 |          29.50 |       32.99 |           29.50
534 …
```
=> Use state plane projection for trees layout, for improved accuracy

src/nyc_trees/apps/core/tasks.py
If the PDF can't be found on the disk after the maximum number of
retries, return None, instead of raising an exception. This ensures that
the RSVP email notification still sends even without the PDF attachment.
How to test:
1. Change an event's map pdf filename to a non-existent file (or delete the pdf inside your VM).
2. RSVP for that event.
3. In celery output you should see it try to find the PDF a few times, then give up, and send the RSVP email anyway.
Refs #1655
=> Send RSVP email even if PDF doesn't exist

src/nyc_trees/apps/event/models.py, src/nyc_trees/apps/event/tests.py
If 12 people RSVP to an event, it should not be possible to decrease the value of max_attendees to 10.
Connects to #1676
=> Prevent decreasing max attendance below RSVP count

src/nyc_trees/apps/event/templates/event/partials/event_form.html, src/nyc_trees/apps/event/views.py
When adding an event, the cancel link should return to the group edit
page. When editing an existing event, the cancel link should go to the
event detail page.
Connects #1679
=> Add context sensitive cancel link

src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html, src/nyc_trees/js/src/surveyPage.js
To test, make sure the following sequences work as described:
When adding a tree:
* header of final tree scrolls to top of visible area
* section of final tree collapses
* new tree is added, and expands
* first input is visible, but not focused
When submitting a form with errors:
* Input with the error is visible
* On platforms other than iOS, input is focused and error message is shown
Thanks to @jfrankl and @maurizi
=> Fix ios scrolling issues

deployment/ansible/roles/nyc-trees.app/templates/gunicorn-nyc-trees.py.j2
The formula for number of Gunicorn workers is:
```
(2 x $num_cores) + 1
```
The application servers are currently m3.mediums, which have 1 core. We were at 2 workers per application server, but following the formula above leaves us with (2 x 1) + 1 = 3.
See also: http://gunicorn-docs.readthedocs.org/en/latest/design.html#how-many-workers
=> Increase number of Gunicorn workers

src/tiler/healthCheck.js
Without explicitly quitting the client the health check slowly consumes all the available connections and starts causing failures.
Running the ``develop`` branch
```
vagrant@tiler:~$ telnet 33.33.33.30 6379
Trying 33.33.33.30...
Connected to 33.33.33.30.
Escape character is '^]'.
CLIENT LIST
$1727
addr=33.33.33.30:39040 fd=5 name= age=1728 idle=87 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=blpop
addr=33.33.33.3:52399 fd=6 name= age=1344 idle=1344 flags=N db=2 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=exec
addr=33.33.33.3:52400 fd=8 name= age=1344 idle=1 flags=N db=2 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=publish
addr=33.33.33.3:52401 fd=9 name= age=1344 idle=0 flags=b db=2 sub=0 …
```
=> Call client.quit after tiler redis health check

src/nyc_trees/apps/core/helpers.py, src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/apps/users/views/group.py
This disables the trusted mapper button on the group detail page if the
user has been approved as a trusted mapper. Some help text is also
displayed.
Connects #1668
=> Disable trusted mapper button if user has been approved

src/nyc_trees/apps/survey/templates/survey/reservations_instructions.html, src/nyc_trees/apps/users/views/user.py
This fixes the "Request independent mapper status" link (step 4) on the
reservations instructions page.
This also fixes a bug where you could bypass training by submitting a
POST to the request mapper status endpoint.
Connects #1694
=> Fix "request mapper status" link on reservations instructions page

src/nyc_trees/apps/event/event_list.py, src/nyc_trees/apps/event/helpers.py, src/nyc_trees/apps/event/models.py, src/nyc_trees/apps/event/templates/event/event_detail.html, src/nyc_trees/apps/event/templates/event/partials/rsvp.html, src/nyc_trees/apps/event/tests.py
This change allows group admins to survey their own events without
taking up an RSVP slot. Clicking the Treecorder link in the nav while
an event is in progress should take the group admin to the event
check-in page.
To test:
1. Login as a group admin with an event in progress (don't RSVP)
2. Click the Treecorder link
3. You should be taken to the "survey for event" page
Connects #1692
=> Allow group admins to survey their own events without needing an RSVP

src/nyc_trees/apps/census_admin/trees.sql
Sorting each aggregate by the tree id ensures all the arrays are in the same order, the order in which the trees were entered.
Test by comparing the ``trees.shp`` files generated by ``dump_db`` in a desktop GIS, before and after the fix.
Before
After
Connects to #1711
=> Fix sorting in tree shapefile query

src/nyc_trees/js/src/progressPage.js
We need to put events on zoomend for the all progress view, but it
interferes with the selection on the user and group views.
We had been explicitly turning the zoomend handler off, but it was only
affecting user progress, not group progress.  Moving the `.off(...)` calls
should make it turn off for both.
Connects to #1697
=> Turn off zoom fixes on the progress map when reloading any layer

deployment/troposphere/app_template.py, deployment/troposphere/tiler_template.py
There are several high traffic periods in the day when mapping events occur. Typically, these happen in bursts and then taper off after an hour or two. In order to protect ourselves during these surges of traffic, scale up and scale down policies have been added to the application and tile servers.
Looking at the ELB graphs for overall request count, a threshold of 60 with a period of 60 seconds and 2 consecutive evaluation periods is a good combination to trigger a scale up event. Before the following minute is over, server capacity doubles.
On the other hand, a threshold of 75 with a period of 60 seconds and 10 consecutive evaluation periods is a safe combination to trigger a scale down event. This is more conservative and protects against lulls between evaluation periods where activity …
=> Add AutoScalingPolicy to application and tile servers

src/nyc_trees/js/src/surveyPage.js
The validation for "Distance to End" was broken by the recent iOS fixes
that scroll the page on validation failures.  The JS was trying to scroll
to the fieldset containing the input that failed validation, but the
Disatnce to End field is not inside a fieldset.
To fix this and prevent future regressions, I have changed it so that we
fall back to scrolling to the input itself if we cannot find a fieldset.
Connects to #1701
=> Fix field validation for the "Distance to End" field

src/nyc_trees/sass/partials/_map.scss
Important for android browsers where the virtual keyboard resizes the
browser window, which can shrink the leaflet map enough to make the search
and leaflet controls conflict.
Connects to #1683
=> Ensure that address search box is above leaflet controls.

src/nyc_trees/apps/survey/layer_context.py, src/nyc_trees/apps/survey/tests.py, src/nyc_trees/apps/survey/views.py, src/tiler/server.js, src/tiler/sql/admin_reservable.sql
Adds a separate reservable layer for census admins, which shows allows
them to map any available unreserved block, regardless of trusted mapper
status for blocks in group territory.
Connects to #199
=> Allow census admins to map any available block, regardless of group.

src/nyc_trees/apps/survey/migrations/0027_recreate_group_territory_20150526_1129.py, src/nyc_trees/apps/users/views/group.py
There was a bug in the view for administering census zones, causing
surveyed block edges to be unassigned when their group's territory was
updated.
This fixes the original issue, and contains a data migration to reassign
those blocks back to their group.
The data migration finds all blocks with no reservations and no territory,
and if they are inside a group polygon, adds them to that group's
territory.  Blocks which are not in any group polygons are assumed to
belong to the 'NYC Parks' group.
Connects to #1717
=> Prevent unassigning group territory for surveyed block edges.

src/nyc_trees/apps/survey/templates/survey/partials/radios.html, src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html, src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/js/src/surveyPage.js, src/nyc_trees/sass/partials/_form-errors.scss
Switches from using builtin browser validation messages to custom messages.
We need to show custom error messages on iOS and older Android browsers, as they will not do so for us.  Since we are doing so for some browsers, I have opted to switch to custom error messages on all browsers.
We still rely on html5 for the actual validation checking, which does work on all mobile browsers.
Connects to #1664
=> Show error validation messages on iOS and old Android browsers

src/nyc_trees/apps/users/templates/groups/detail.html, src/nyc_trees/sass/partials/_home.scss
Mouseover effect does not show on group page. Adding ```.circles-nohover``` to ```.progress-circles``` will remove this effect from any group of progress circles.
Fixes #1735.
=> Remove mouseover effect on progress circles on a group's page

src/nyc_trees/apps/survey/migrations/0028_update_layoutboxes_20150529_1328.py, src/nyc_trees/apps/survey/migrations/layoutBoxes.sql
Pulled in from https://github.com/treekit/treekit
The most important part of this update is https://github.com/treekit/treekit/commit/1ef16d75d4a4b54b90deedc1601b2c110d0c2058 which fixes a problem where null geometries were created for trees on short blocks.
Connects to #1728
=> Update layoutBoxes to 67a5f279 version

src/nyc_trees/apps/survey/admin.py
connects to #1696 on github
we never want the user to be able to edit it, and it also is not working
as currently implemented.
=> Hide geom field in blockface admin

src/nyc_trees/apps/event/views.py
This fixes the case where sending event emails for groups with no group
admin would throw an exception.
To test:
1. Find an event for a group with no group admin (or set the group
admin to null)
2. Send a bulk event email
3. Email should send successfully
Connects #1739
=> Fix exception when sending bulk event email

deployment/requirements.txt, deployment/troposphere/app_hosted_zone_template.py, deployment/troposphere/app_template.py, deployment/troposphere/tiler_template.py
In the process of creating a new stack from an existing template, the following resources and their parameters became stale and required updates:
- CloudFront Distribution/MinimumProtocolVersion
If you specify the `IamCertificateId` property and specify SNI only for the `SslSupportMethod` property, you must use `TLSv1` for the minimum protocol version. If you don't specify a value, AWS CloudFormation specifies `SSLv3`.
- AutoScalingGroup/NotificationConfigurations
`NotificationConfiguration` is now `NotificationConfigurations` (plural) and now accepts an array of `NotificationConfigurations`.
=> Update CloudFormation templates so that resources are up-to-date

src/nyc_trees/apps/event/event_list.py
"Your Events This Week" on the Events page wasn't showing a user's private events.
* Removed the `is_private=False` filter from `EventList.immediate_events`
* That routine is used nowhere else, so the change is safe
The dashboard wasn't showing a user's private events.
* Removed the `is_private=False` filter from `EventList.all_events`
* That routine is also used with the `EventList.trainingFilters`
so they need an `is_private=False` filter
* I believe that no other lists are affected by this change, and I think I tested them all,
but with the multiple levels of indirect linkages it's hard to tell
Connects #1754
=> Show private events in user event lists

src/nyc_trees/js/src/event_list_page.js, src/nyc_trees/js/src/map.js, src/nyc_trees/js/src/progressPage.js
This is intended to prevent the blockface tile layer from obscuring the
street names, to help in identifying the correct blockface while mapping.
I kept the progress map as it was, because I was running into issues
with labels interfering with the labels on the aggregate neighborhood
and borough layers.
I also excluded the event list map and the survey detail map, because
they do not have a blockface layer, so there is no need for a separate
label layer.
Thanks to @jwalgran for the initial implementation!
Connects to #1759 
To test, please check that labels are visible and above the blockface layer on the following maps: reservations, treecorder, census zone administration, reservations PDF, and event PDF.
=> Use stamen toner labels on top of a label-less basemap for most maps.

src/nyc_trees/js/src/surveyPage.js
Without this change I saw multiple posts when clicking "Submit" multiple times.
With this change I only saw one submit.
I also verified that you can't submit the same data twice by using the browser back button.
Connects #1765
=> If submit succeeds, don't reenable the submit button

src/tiler/style/progress.mss
Some of the neighborhood polygons on the progress map have centroids that
lie outside the polygon, which leads to their percentage label being
placed inside a different neighborhood (which will then have two labels).
By adding `text-placement: interior` to the CartoCSS, we tell Mapnik to
prefer placing labels on the interior of polygons if the centroid is not
inside the poygon.
Prior to this fix:
After:
=> Fix label positions on the progress map for concave polygons.

src/nyc_trees/js/src/lib/mapUtil.js, src/nyc_trees/js/src/map.js, src/nyc_trees/js/src/searchController.js
This commit introduces a new zoom level "preset" to be used when zooming to the geolocation of the device, or to the location of a mapping event. This is a usability improvement suggested by Parks based on feedback from mapping events.
Geolocation zoom before
After
Connects to #1749
=> Set a higher zoom level when zooming to a location

src/nyc_trees/js/src/map.js, src/nyc_trees/js/src/surveyPage.js
For testing, points near Azavea are shown in southern Manhattan.
To test:
* Use a mobile device (ideally a tablet, wide enough to show both the map and the input form)
* Reserve some blocks at the southern tip of Manhattan
* Open Treecorder. You should see a green dot somewhere around there.
* Walk around. The dot should move.
* Start entering data. The dot should disappear.
Connects #1764
=> Show user location on Treecorder map

src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/sass/partials/_survey.scss
We are updating the text in an attempt to avoid some common problems that Parks is seeing in the field.
The increase in the amount of text in the "which side of the street" question required shrinking the size of the map.
Before
After
Connects to #1763
=> Update treecorder instructional text

src/nyc_trees/apps/event/templates/event/partials/teammate_item.html, src/nyc_trees/apps/event/templates/event/partials/teammates.html, src/nyc_trees/apps/survey/helpers.py, src/nyc_trees/apps/survey/routes.py, src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/apps/survey/urls/survey.py, src/nyc_trees/apps/survey/views.py, src/nyc_trees/js/src/surveyPage.js
The select tag based autocomplete was proving to be not performant enough
with a significant number of users (over 3000).
Moving to an AJAX-based autocomplete should alleviate the performance
issues we have encountered with it.
Connects to #1726
=> Remove inline teammate autocomplete in favor of AJAX backed autocomplete

src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/login/forms.py, src/nyc_trees/apps/login/urls/login.py, src/nyc_trees/libs/auth_backend.py, src/nyc_trees/nyc_trees/settings/base.py
This allows email login for both normal login and the Django Admin site,
but I only updated the labels and error messages for the normal login page.
Connects to #1777
=> Allow logging in via either username or email address

src/nyc_trees/apps/event/views.py, src/nyc_trees/apps/survey/layer_context.py, src/nyc_trees/apps/survey/templates/survey/survey_detail.html, src/nyc_trees/js/src/map.js, src/tiler/server.js, src/tiler/sql/event_pdf.sql, src/tiler/style/event_pdf.mss
Here's a shot from the event map PDF. 
In B/W :
Connects #1780 
Connects #1779
=> Fix initial map zoom levels, and show mapped/unmapped blocks on event map PDF

src/nyc_trees/apps/event/migrations/0015_auto_20150730_1735.py
Note we did this before this is copied from `src\nyc_trees\apps\event\migrations\0012_auto_20150424_1705.py`
Connects #1787
=> Add data migration causing all event map PDFs to be regenerated

src/nyc_trees/apps/login/routes.py, src/nyc_trees/apps/login/templates/login/password_reset_activation_email.html, src/nyc_trees/apps/login/templates/login/password_reset_impossible.html, src/nyc_trees/apps/login/templates/login/send_activation_email.html, src/nyc_trees/apps/login/urls/accounts.py, src/nyc_trees/apps/login/urls/login.py, src/nyc_trees/apps/login/views.py
Connects to #1783 
When attempting a password reset for a user that registered less than 7 days ago:
When attempting a password reset for a user that registered more than 7 days ago:
Blocked waiting for confirmation of the text.
=> Add pages for resending activation emails on a failed password reset.

src/nyc_trees/libs/pdf_maps.py
Shelling out to PhantomJS happens within a function that takes session ID as an argument. That session ID is then passed to PhantomJS via command line arguments.
For reservation PDFs, the session ID is needed to tailor the map for the user who reserved. For event PDFs, no session ID is needed, but it still goes through the same function as reservation PDFs. In cases where the user who triggered an event PDF regeneration is logged out, the session ID is `None`, which `execv` (inside `subprocess.check_output`) doesn't like. It expects all arguments to be Python strings.
=> Fix event map PDF generation triggered by logged out users

src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/home/views.py, src/nyc_trees/apps/survey/helpers.py, src/nyc_trees/apps/survey/models.py, src/nyc_trees/apps/survey/templates/survey/partials/progress_page_blockface_popup.html, src/nyc_trees/apps/survey/views.py, src/nyc_trees/libs/sql.py, src/nyc_trees/sass/partials/_legend.scss, src/tiler/sql/borough_progress.sql, src/tiler/sql/event_pdf.sql, src/tiler/sql/group_progress.sql, src/tiler/sql/nta_progress.sql, src/tiler/sql/progress.sql, src/tiler/sql/user_progress.sql, src/tiler/style/progress.mss
Surveys quit for a specific reason (intended for things which prevent
mapping the block edge, like construction) are now considered as
completed for the purposes of aggregate counts such as percent completed
on the home page and the block and neighborhood percentages on the
progress map.
For the more detailed view of the all progress layer, and for the user and
group progress layers, we show quit blocks as gray, and the legend shows
that they could not be mapped.
On the event detail map, I chose to show quit blocks the same color as mapped
blocks, since the more pertinent information there is what is available.
Connects to #1800
=> Count quit surveys as completed for aggregate counts.

src/nyc_trees/js/src/adminTerritoryPage.js, src/nyc_trees/js/src/lib/BlockfaceLayer.js
This should allow determining what color the underlying block edge is,
and if it is mapped or unmapped, while still making it easy to determine
which block edges are selected or unselected.
Connects to #1801
=> Make the territory map selected blocks dashed.

src/nyc_trees/apps/survey/migrations/0029_survey_submit_comment.py, src/nyc_trees/apps/survey/models.py
Temporarily allowing null values allows the migrated database to be shared between old and new versions of the running application, making blue/green deployments easier to manage.
Connects to #1808
=> Make survey migration 0029 backward compatible

src/nyc_trees/apps/survey/migrations/0030_auto_20150901_1244.py, src/nyc_trees/apps/survey/models.py
Now that we have pushed release 12 into production, it should be safe
to remove the `null=True` from this field.
Connects to #1810
=> Make Survey.submit_comment non-nullable again.

src/nyc_trees/js/src/map.js
This works well, except that I'm getting 503 errors on Stamen label tiles
at zoom 19 (our default zoom for many block edges) and on some tiles at zoom 18.
I don't think it's our problem since I also see these errors at their site, e.g.
http://maps.stamen.com/toner-labels/#18/40.71925/-73.99044
I reported the problem using their "report a bug" form.
Connects #1813
=> Show street label layer on survey detail page

src/nyc_trees/apps/home/templates/home/about_faq.html
A new answer for "When will TreesCount! 2015 end?" provides by Parks.
Connects to #1818
=> Change census end FAQ text.

src/nyc_trees/apps/core/templates/core/partials/nav.html, src/nyc_trees/apps/event/event_list.py, src/nyc_trees/apps/event/templates/event/partials/rsvp.html, src/nyc_trees/apps/home/templates/home/partials/dashboard.html, src/nyc_trees/apps/home/templates/home/partials/home_public.html, src/nyc_trees/apps/home/templates/home/partials/training.html, src/nyc_trees/apps/users/templates/groups/partials/event_section.html, src/nyc_trees/apps/users/templates/groups/partials/follow_button.html, src/nyc_trees/apps/users/templates/groups/partials/follow_detail.html, src/nyc_trees/apps/users/templates/users/partials/activity.html, src/nyc_trees/nyc_trees/middleware.py, src/nyc_trees/nyc_trees/settings/base.py
Uses the existing soft launch infrastructure to support full access to
the site when the census is suspended to a limited group of people, and
allow some access for other users.
Users who do not have full access can get to the progress map, group and
event lists, group and event detail pages, the FAQ and the main training
page (but not the training subpages).
Access to editing groups and events is blocked off unless the user has
full site access, as is access to following groups.
Connects to #1814 
To test, configure the `full_access` waffle flag from the Django admin site.  You can set the value for `Everyone` to `No` to test how limited access works regardless of the logged in user, or set the flag to `Unknown` to allow configuring which users the flag does and does not apply to via the …
=> Add support for limiting access to the site after the census ends.

src/nyc_trees/apps/event/templates/event/event_detail.html
Regular users cannot RSVP to events after the census officially ends.
Connects to #1826
=> Hide RSVP button unless user has full_access

src/nyc_trees/apps/event/templates/event/event_list_page.html, src/nyc_trees/apps/home/templates/home/about_faq.html, src/nyc_trees/apps/home/templates/home/partials/dashboard.html, src/nyc_trees/apps/home/templates/home/partials/home_public.html, src/nyc_trees/apps/survey/templates/survey/partials/reservations_legend.html, src/nyc_trees/apps/users/templates/groups/list.html, src/nyc_trees/apps/users/templates/users/achievement.html, src/nyc_trees/apps/users/templates/users/partials/activity.html, src/nyc_trees/apps/users/templates/users/partials/profile/reservations.html, src/nyc_trees/templates/registration/activation_email.html, src/nyc_trees/templates/registration/registration_form.html
* Leave existing text commented-out for easy restoration in spring
* On the logged-in dashboard I gave them a slightly different order than they requested. (It would be a lot harder to have events in the middle because of how this content is shared with the user profile.):
* Currently: events, groups, reservations, rewards
* They wanted: reservations, rewards, events, groups
* I gave them: reservations, rewards, groups, events
Connects #1825
=> Apply "winter" text changes from Parks

deployment/ansible/roles/nyc-trees.app/tasks/dev-and-test-dependencies.yml
The latest version of Firefox is 41, which wasn't matched by the filter.
Connects to #1831
=> Fix firefox provisioning.

src/nyc_trees/apps/event/templates/event/event_list_page.html
There will be no events over the winter so this instructive text could
be misleading.
Connects to #1825
=> Hide calls to action on event page

src/nyc_trees/apps/core/templates/core/partials/nav.html, src/nyc_trees/apps/event/event_list.py, src/nyc_trees/apps/users/templates/groups/partials/edit_event_list.html, src/nyc_trees/apps/users/views/group.py
* Remove "Events" page from menu
* Remove "Current" section from group events
* Remove "+ New" option when editing a group
To allow possible future use of the code I chose to comment out rather than delete.
Connects #1837
=> Reduce access to events

deployment/ansible/roles.txt, deployment/ansible/roles/nyc-trees.beaver/vars/main.yml
The latest version of azavea.beaver uses 36.2.0 for the beaver version.
Only the most recent version of Beaver can be installed, as one of its
dependencies was renamed and old versions were pulled from PyPi.
=> Update the azavea.beaver ansible role to the latest version

src/nyc_trees/apps/home/tests.py, src/nyc_trees/apps/survey/tests.py, src/nyc_trees/apps/users/__init__.py, src/nyc_trees/apps/users/migrations/0008_auto_20160415_1550.py, src/nyc_trees/apps/users/migrations/0009_record_2015_achievements.py, src/nyc_trees/apps/users/models.py, src/nyc_trees/apps/users/tests.py
New achievements are temporarily using the image for 'Mayoral Mapper'
until the final images are decided upon.
To enable showing what achievements a user already has, a data migration
will update achievements for all users to record their what their inactive
achievements are, since they are no longer active for 2016 and cannot be
unlocked with new surveys.
Connects to #1836
=> Add new achievements

src/nyc_trees/apps/survey/templates/survey/progress.html
We omitted the dropdown from the progress map when logged out, because
after removing the group view in 83aa2242 there was only a single mode
when not logged in.
This broke loading the tiles on the page, as JS reads the DOM to know
which mode is currently active.  Hiding the element instead of omitting it
fixes the issue while still leaving it not shown for logged out users.
Connects to #1845
=> Fix loading tiles on progress map when logged out

src/nyc_trees/apps/core/admin.py, src/nyc_trees/apps/core/migrations/0032_user_survey_preview_help_shown.py, src/nyc_trees/apps/core/models.py, src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/apps/survey/views.py, src/nyc_trees/js/src/surveyPage.js
To test, log in, reserve a block edge, and visit the treecorder.
Upon first getting to the data entry part of the treecorder you should see
a modal.  On later uses of the treecorder you should not see a modal.
Connects to #1842
=> Show preview button help popup when first visiting the treecorder

src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/js/src/surveyPage.js, src/nyc_trees/sass/partials/_survey.scss
On mobile the ID is visible at all times on the preview button (previewing itself is not implemented yet).
I attempted to make the header "sticky" for the desktop view so that the blockface ID would always be visible for desktop users as well, but I ran into cross-browsers styling issues and decided to leave it as-is.
Connects to #1840
=> Show blockface ID on treecorder screen.

src/nyc_trees/apps/survey/routes.py, src/nyc_trees/apps/survey/survey_detail.sql, src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/apps/survey/tests.py, src/nyc_trees/apps/survey/urls/survey.py, src/nyc_trees/apps/survey/views.py, src/nyc_trees/js/src/surveyPage.js, src/nyc_trees/sass/partials/_survey.scss
Builds on top of 4a26f2f, which is not part of this PR.
Alters `survey_detail.sql` to operate based on passed in parameters,
allowing us to show a preview screen without having to save the survey to
the database.
To test:
- Ensure there are no regressions in showing the survey detail page
- Test that the survey preview looks correct
- Test that the scroll position is correct and all elements are shwon/hidden appropriately after showing/hiding the preview
Connects to #1841
=> Add ability to preview survey before submitting it

src/nyc_trees/apps/survey/templates/survey/survey.html, src/nyc_trees/js/src/map.js, src/nyc_trees/js/src/surveyPage.js, src/nyc_trees/sass/partials/_survey.scss
- Add button to survey preview to restart survey.
- Slight style fix to tree sponsor section on mobile
- Improve setting bounds when showing preview map, and prevent zooming or panning away from the blockedge
Connects to #1858 
Connects to #1859
=> Survey preview improvements

deployment/packer/template.js
The loose dependency on Paramiko is pulling in a version with a backwards incompatible change, which is causing the Ansible install to fail. Until Ansible addresses this issue, I'd rather explicitly install an older version of Paramiko that satisfies Ansible dependency requirements.
See also: ansible/ansible#15665
---
**Testing**
See if http://civicci01.internal.azavea.com/view/nyc-trees/job/nyc-trees-packer/647/ succeeds.
=> Meet Paramiko dependency before installing Ansible

src/nyc_trees/js/src/surveyPage.js
When changing the map element size (e.g if the phone orientation changes),
if the map is not currently visible it will get stuck in an invalid state.
Calling `.invalidateSize()` when switching between the preview map and the
normal survey map will cause Leaflet to requery the DOM for the map size,
fixing the issue.
I wasn't able to create issues with the normal survey map, but I put in a call to `invalidateSize()` for it when hiding the preview map, since it can't really hurt matters.
To test:
- On the develop branch, show the preview map, close it, resize the browser window, and show the preview map again.  You should see the issue reported in #1867.
- On this branch, repeat the same steps.  You should not experience the issue.
Connects to #1867
=> Fix map not showing when switching between preview map and normal map

deployment/ansible/group_vars/all, deployment/ansible/roles.yml
Version 7u95 of the OpenJDK JVM is no longer available.
See also: azavea/ansible-apache2#5
=> Bump Apache and JVM versions

deployment/deployment-helper.sh, deployment/requirements.txt, deployment/troposphere/app_hosted_zone_template.py, deployment/troposphere/tiler_hosted_zone_template.py
Ensure that we are supplying arguments to the `AliasTarget` resource in the correct way. Previously, keyword arguments were not available, so the order of constructor arguments meant something. That meaning was altered along the way, which led to silent parameter swapping.
---
**Testing**
The [`nyc-trees-staging-deployment`](http://civicci01.internal.azavea.com/view/nyc-trees/job/nyc-trees-staging-deployment/497/console) job in Jenkins already executed a deployment to staging with the changes in this PR. Ensure that the application is working correctly with whatever new changes were introduced.
=> Use AliasTarget keyword arguments for parameters
