azavea/nyc-trees

src/nyc_trees/apps/home/templates/home/home.html
src/nyc_trees/apps/home/templates/home/progress.html
src/nyc_trees/gulpfile.js
src/nyc_trees/js/src/map.js
src/nyc_trees/js/src/progressPage.js
src/nyc_trees/npm-shrinkwrap.json
src/nyc_trees/package.json

* Using OpenStreetMap data for now
* Initial extent includes all of New York City
* The map is not currently 100% height, pending styling fixes from the design team
* `map.js` is currently very simple, and will presumably sprout more options

Add progress map page

---

src/nyc_trees/apps/core/test_utils.py
src/nyc_trees/apps/event/tests.py
src/nyc_trees/apps/survey/migrations/0003_auto_20141231_1235.py
src/nyc_trees/apps/survey/models.py
src/nyc_trees/apps/users/templates/groups/detail.html
src/nyc_trees/apps/users/tests.py
src/nyc_trees/apps/users/views/group.py
src/nyc_trees/apps/users/views/user.py
src/nyc_trees/libs/sql.py

Also fixes a TODO on the existing user profile contributions section

Add Group contributions section

---

src/nyc_trees/requirements/base.txt

Bugfix release: https://docs.djangoproject.com/en/dev/releases/1.7.2/

Bump Django version to 1.7.2

---

src/nyc_trees/apps/home/routes.py
src/nyc_trees/apps/home/templates/home/partials/legend.html
src/nyc_trees/apps/home/templates/home/progress.html
src/nyc_trees/apps/home/urls.py
src/nyc_trees/apps/home/views.py
src/nyc_trees/js/src/map.js
src/nyc_trees/js/src/progressPage.js
src/nyc_trees/sass/main.scss
src/nyc_trees/sass/partials/_legend.scss

* Change `home` app to routes pattern
* Add `legend.html` template with bootstrap modal
* Legend entries are context-driven, with CSS class to define color
* Add "legend" button to map

Add legend to progress map

---

src/nyc_trees/apps/core/templates/base_two_frames.html
src/nyc_trees/apps/users/templates/groups/detail.html
src/nyc_trees/apps/users/templates/groups/settings.html
src/nyc_trees/apps/users/templates/users/profile.html
src/nyc_trees/apps/users/templates/users/settings.html
src/nyc_trees/apps/users/tests.py
src/nyc_trees/sass/partials/_globals.scss

Abstract common page layout code for two column layout. Pages should look the same.

Add template for common two column display

---

templates/default.html

Add a default template that developers can use when they're working on a new page.

Add default template

---

src/nyc_trees/apps/event/templates/event/event_detail.html
src/nyc_trees/apps/event/templates/event/partials/rsvp.html
src/nyc_trees/sass/partials/_globals.scss
src/nyc_trees/sass/partials/_variables.scss

Add styling

---

src/nyc_trees/apps/event/templates/event/add_event.html
src/nyc_trees/apps/event/templates/event/edit_event.html
src/nyc_trees/apps/event/templates/event/event_list_page.html
src/nyc_trees/apps/event/templates/event/partials/event_form.html
src/nyc_trees/sass/partials/_globals.scss

Converting a few more event pages to the new template

Switch event pages to two frame template

---

src/nyc_trees/apps/users/views/group.py

It is unclear to me why this only started failing recently.

Fix broken unit test

---

src/nyc_trees/apps/core/templates/core/partials/config.js
src/nyc_trees/apps/survey/migrations/0006_auto_20150113_1533.py
src/nyc_trees/apps/survey/models.py
src/nyc_trees/apps/users/migrations/0003_auto_20150113_1210.py
src/nyc_trees/apps/users/models.py
src/nyc_trees/nyc_trees/context_processors.py
src/nyc_trees/nyc_trees/settings/base.py
src/nyc_trees/nyc_trees/tests.py
src/tiler/npm-shrinkwrap.json
src/tiler/package.json
src/tiler/server.js
src/tiler/sql/progress.sql
src/tiler/sql/user_progress.sql
src/tiler/style/progress.mss

- Expands the progress layer to show survey/reservation information
- Refactors the context processor / tiler URL generation
- Adds a watch command for the tiler

Add styling and UTF8grid data to progress map tile layer

---

src/nyc_trees/apps/home/views.py
src/nyc_trees/sass/partials/_legend.scss
src/tiler/style/progress.mss

* Use different legend entries depending on whether user is logged in
* Use the same names and colors the tiler uses

Legend is user-aware and colors match tiler colors

---

README.md

Remove the port override section from the README

---

src/nyc_trees/apps/core/templates/404.html

I was unable to test this because of configuration issues. (You can view a 404 page with development settings by setting `DEBUG = False` and `ALLOWED_HOSTS = ['*']`, but that caused 500 errors I was unable to diagnose.)
Posting as work-in-progress.

Custom 404 page

---

README.md
deployment/requirements.txt

This changeset adds Ansible to the deployment dependency requirements. The version listed here should govern what's supported for local provisioning and in CI.

Add Ansible dependency to deployment requirements

---

src/nyc_trees/npm-shrinkwrap.json
src/nyc_trees/package.json

Update browserify and watchify versions

---

src/nyc_trees/apps/core/migrations/0009_auto_20150120_1941.py
src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/login/backends.py
src/nyc_trees/apps/login/forms.py
src/nyc_trees/apps/login/routes.py
src/nyc_trees/apps/login/urls/accounts.py
src/nyc_trees/apps/login/urls/login.py
src/nyc_trees/apps/login/views.py
src/nyc_trees/js/src/activation_form.js
src/nyc_trees/templates/registration/activation_complete.html

To test:
1. Go to http://localhost:8000/accounts/activate/complete/
1. Confirm your input is recorded via Django admin

Optional info form

---

src/nyc_trees/apps/core/test_utils.py
src/nyc_trees/apps/event/forms.py
src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/event/templates/event/add_event.html
src/nyc_trees/apps/event/templates/event/edit_event.html
src/nyc_trees/apps/event/templates/event/partials/event_form.html
src/nyc_trees/apps/event/templates/event/partials/event_form_with_maps.html
src/nyc_trees/apps/event/views.py
src/nyc_trees/js/src/EventMap.js
src/nyc_trees/js/src/event.js
src/nyc_trees/js/src/event_form.js
src/nyc_trees/js/src/event_map.js
src/nyc_trees/js/src/map.js
src/nyc_trees/nyc_trees/context_processors.py

* `EventMap.js` creates a map with a highlighted and changeable location
* On AddEvent/EditEvent pages add a second pane with a large map
* Show static crosshairs on the large map
* Modify location via "Edit" "Done", and "Cancel" operations
* Require saved location to be within New York City bounds

Allow changing event location on a large map

---

src/nyc_trees/apps/core/templates/base.html
src/nyc_trees/apps/quiz/models.py
src/nyc_trees/apps/quiz/routes.py
src/nyc_trees/apps/quiz/templates/quiz/quiz_complete_page.html
src/nyc_trees/apps/quiz/templates/quiz/quiz_list_page.html
src/nyc_trees/apps/quiz/templates/quiz/quiz_page.html
src/nyc_trees/apps/quiz/tests.py
src/nyc_trees/apps/quiz/urls.py
src/nyc_trees/apps/quiz/utils.py
src/nyc_trees/apps/quiz/views.py
src/nyc_trees/gulpfile.js
src/nyc_trees/js/src/quiz.js

1. You should be able to access the intro quiz here: [http://localhost:8000/quiz/](http://localhost:8000/quiz/)
2. Completing a quiz should record your result here: [http://localhost:8000/admin/users/trainingresult/](http://localhost:8000/admin/users/trainingresult/)
3. Re-taking the quiz should preserve your highest score (If you score a 2, then re-take the quiz and score a 1, your score in the DB should remain a 2)

Add training quiz

---

deployment/ansible/filter_plugins/custom_filters.py

This changeset adds an explicit method signature to the Ansible custom filters.

Add explicit method signature to custom filters

---

src/nyc_trees/js/src/searchController.js

Stop mouse event propagation on map search control

---

src/nyc_trees/apps/survey/routes.py
src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html
src/nyc_trees/apps/survey/views.py
src/nyc_trees/js/shim/leaflet.utfgrid-src.js
src/nyc_trees/js/src/reserveBlockfacePage.js
src/nyc_trees/js/src/selectableBlockfaceLayer.js
src/nyc_trees/package.json
src/tiler/server.js
src/tiler/sql/user_reservable.sql
src/tiler/style/progress.mss

This is only the client-side portion of reserving blockfaces.
More work will need to be done in a future PR to post the blockface ids
to the server in order to reserve them.
Selected blockfaces will have a vector line laid overtop of them to
indicate that they are currently selected.
This was abstracted into `selectableBlockfaceLayer.js` for reuseability with
other pages where we will need to show the currently selected blockface(s)

Reservation selection

---

src/nyc_trees/apps/core/mail/backends/boto.py
src/nyc_trees/libs/boto_mailer.py
src/nyc_trees/nyc_trees/settings/production.py
src/nyc_trees/requirements/production.txt

Using boto on a properly provisioned EC2 keeps the application out of the business of managing email credentials.
All boto interaction is isolated in the ``BotoMailer`` class, which has no dependencies on Django and can be tested in isolation.
This backend is configured for production only because it requires EC2 metadata services that aren't available on vagrant VMs.

Add SES/boto based email backend for prod

---

src/nyc_trees/apps/quiz/templates/quiz/quiz_complete_page.html
src/nyc_trees/apps/quiz/templates/quiz/quiz_list_page.html
src/nyc_trees/apps/quiz/templates/quiz/quiz_page.html
src/nyc_trees/templates/registration/registration_complete.html

This URL to the training summary page changed recently.

Fix training summary URL references

---

src/nyc_trees/apps/survey/routes.py
src/nyc_trees/apps/survey/templates/survey/partials/reserved_blockface_popup.html
src/nyc_trees/apps/survey/templates/survey/reservations.html
src/nyc_trees/apps/survey/urls/blockface.py
src/nyc_trees/apps/survey/views.py
src/nyc_trees/js/src/reservationPage.js
src/nyc_trees/js/src/selectableBlockfaceLayer.js
src/tiler/server.js
src/tiler/sql/user_reservations.sql

An HTML partial is loaded via AJAX when a blockface is selected, and
used to populate the actionbar at the bottom of the page.

My reservations action bar

---

src/nyc_trees/apps/core/mail/backends/boto.py

This changeset fixes the custom e-mail backend we're using to send e-mail from Django through AWS SES.

Fix SES/Boto mailer

---

src/nyc_trees/gulpfile.js
src/nyc_trees/js/src/reserveBlockfacePage.js
src/nyc_trees/npm-shrinkwrap.json
src/nyc_trees/package.json

This adds a little toastr notification when you click on unavailable blockfaces.
1. You'll need to reserve a chunk of blockfaces. Here's a query that reserves a nice chunk (for user ID 2):
insert into survey_blockfacereservation (user_id, created_at, updated_at, expires_at, is_mapping_with_paper, blockface_id) select 2, now(), now(), now() + interval '1 month', FALSE, 24197 union all select 2, now(), now(), now() + interval '1 month', FALSE, 24199 union all select 2, now(), now(), now() + interval '1 month', FALSE, 24200 union all select 2, now(), now(), now() + interval '1 month', FALSE, 24202 union all select 2, now(), now(), now() + interval '1 month', FALSE, 24203 union all select 2, now(), now(), now() + interval '1 month', FALSE, 24204 union all select 2, now(), …

Display popup notification for unavailable blockfaces

---

src/nyc_trees/apps/core/migrations/0013_user_field_training_complete.py
src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/event/tests.py
src/nyc_trees/apps/event/views.py

This field is set to True on the user model when they have been checked
into a training event.

Add field_training_complete field

---

src/nyc_trees/apps/core/migrations/0014_auto_20150203_1604.py
src/nyc_trees/apps/core/models.py

Don't require group image, contact url, admin

---

deployment/MIGRATIONS.md

This changeset adds documentation for the process of applying migrations to an AWS stack of this project.

Add documentation for applying migrations

---

src/nyc_trees/apps/home/templates/home/partials/training.html
src/nyc_trees/apps/home/views.py

Gate Training headline based on completion

---

src/nyc_trees/apps/home/templates/home/partials/dashboard.html
src/nyc_trees/apps/home/tests.py
src/nyc_trees/apps/home/views.py
src/nyc_trees/apps/users/__init__.py
src/nyc_trees/apps/users/templates/users/partials/activity.html
src/nyc_trees/apps/users/templates/users/profile.html
src/nyc_trees/apps/users/views/user.py

The dashboard shows much of the same content as the user profile page. I have extracted the context generation helpers out of the users view file so they can be more easily shared with the home app.

Add profile widgets to the dashboard

---

src/nyc_trees/apps/core/templates/base.html
src/nyc_trees/apps/core/templates/core/partials/nav.html
src/nyc_trees/apps/event/templates/event/event_list_page.html
src/nyc_trees/apps/home/templates/home/home.html
src/nyc_trees/apps/home/templates/home/training.html
src/nyc_trees/apps/survey/templates/survey/reservations.html
src/nyc_trees/apps/users/templates/groups/list.html

Moves nav into a partial so we can highlight the active page in the
side nav.
Fixes #418.

Highlight active page in nav

---

src/nyc_trees/apps/home/templates/home/quiz_page.html
src/nyc_trees/apps/home/tests.py
src/nyc_trees/apps/home/training/__init__.py
src/nyc_trees/apps/home/training/types.py
src/nyc_trees/js/src/quiz.js

The first question of the training quiz is now a multiple choice question to demonstrate this feature.

Add support for checkboxes on training quiz

---

src/nyc_trees/apps/event/routes.py
src/nyc_trees/apps/event/templates/event/user_checkin.html
src/nyc_trees/apps/event/tests.py
src/nyc_trees/apps/event/urls/group.py
src/nyc_trees/apps/event/views.py
src/nyc_trees/gulpfile.js
src/nyc_trees/js/src/userCheckinPage.js

This will poll an endpoint every few seconds to determine if the user has
been checked-in by an admin yet. When the user is checked-in they will
be redirected to the event detail page.

Add polling to user event checkin page

---

src/nyc_trees/apps/event/event_list.py
src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/event/templates/event/event_detail.html
src/nyc_trees/apps/event/templates/event/partials/event_section.html
src/nyc_trees/apps/event/templates/event/partials/rsvp.html
src/nyc_trees/apps/event/views.py
src/nyc_trees/apps/users/templates/groups/partials/event_section.html
src/nyc_trees/js/src/copyEventUrl.js
src/nyc_trees/js/src/event.js
src/nyc_trees/js/src/group_detail.js
src/nyc_trees/js/src/group_settings.js

Fix actions in event dropdowns on group admin "Events" tab

---

src/nyc_trees/apps/core/templates/core/partials/nav.html
src/nyc_trees/apps/home/templates/home/progress.html

Add progress map to nav bar

---

src/nyc_trees/apps/event/views.py
src/nyc_trees/apps/users/templates/groups/settings.html
src/nyc_trees/apps/users/views/group.py
src/nyc_trees/js/src/group_settings.js
src/nyc_trees/js/src/lib/tabhash.js

Redirect to event tab on group edit after adding

---

src/nyc_trees/apps/home/templates/home/partials/home_public.html

Link "Create an Account" button to /accounts/register/

---

src/nyc_trees/js/src/map.js

Parks likes the general look of Toner. Swapping in to see how it looks in context.
Fixes #515

Switch to Stamen Toner basemap

---

src/nyc_trees/apps/home/templates/home/groups_to_follow.html
src/nyc_trees/apps/users/templates/groups/list.html

Add search functionality to groups list page

---

src/nyc_trees/apps/users/templates/users/profile.html
src/nyc_trees/apps/users/tests.py

Restore privacy popup

---

src/nyc_trees/apps/core/templates/base.html
src/nyc_trees/sass/partials/_header.scss

Fix ie layout glitch. Fixes #485

---

src/nyc_trees/apps/home/templates/home/quiz_page.html

Add 'check all applicable' text to multi-answer qs

---

src/nyc_trees/apps/home/templates/home/partials/dashboard.html
src/nyc_trees/apps/home/views.py
src/nyc_trees/js/src/home.js

Implement 'This week's events' on dashboard

---

src/nyc_trees/apps/home/templates/home/partials/training.html
src/nyc_trees/apps/home/training/types.py

Add class for inactive training steps for styling

---

deployment/troposphere/data_store_template.py

This changeset adds several CloudWatch alarms to the data stores (RDS, ElastiCache).
The RDS alarms are based on:
- CPUUtilization
- FreeableMemory
- FreeStorageSpace
- DiskQueueDepth
The ElastiCache alarms are based on:
- CPUUtilization
- FreeableMemory
The alarms have already been applied to staging. You can view them on the CloudWatch alarms page.
---

Add CloudWatch alarms to data stores

---

src/nyc_trees/apps/users/templates/groups/partials/event_section.html

Remove unnecessary `.date` to resolve timezone issue

---

src/nyc_trees/apps/event/templates/event/event_detail.html

Show time on event detail page

---

src/nyc_trees/apps/core/templates/core/partials/nav.html

Hide user navigation if not logged in

---

src/nyc_trees/js/src/trainingFlatpage.js

Don't show 'Back' button on exercise failure

---

src/nyc_trees/sass/partials/_map.scss

Fix actionbar dropup menu appearing under the leaflet map.

---

src/nyc_trees/templates/floppyforms/attrs.html

Fix floppyforms checkbox attributes template

---

src/nyc_trees/apps/survey/templates/survey/reservations_instructions.html

Forgot to include this in my last merged PR.

Add missing template

---

src/nyc_trees/js/src/mapUtil.js

Revert 6914a00d4 because it broke 'add event' map

---

src/nyc_trees/js/src/reservationPage.js
src/nyc_trees/js/src/searchController.js

The export was changed from zoom to ZOOM but not all the references were updated.

Fix references to mapUtil.ZOOM

---

src/nyc_trees/apps/home/templates/home/quiz_page.html
src/nyc_trees/apps/home/tests.py
src/nyc_trees/apps/home/training/__init__.py
src/nyc_trees/apps/home/training/types.py

This merges Question and MultiChoiceQuestion (all questions are
multiple choice). This also adds strongly typed classes for the answer
field to differentiate between checkbox & radio button questions.
This is not a priority for user testing.

Refactor quiz classes

---

src/nyc_trees/apps/users/tests.py

This tests for a regression against
6d2bcb358589682c8e0d864b95449784a1e1fc73.

Test that logged out users can view group detail page

---

src/nyc_trees/apps/core/templates/base.html

Use static_url template filter for footer image.

---

src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/event/views.py
src/nyc_trees/apps/users/__init__.py
src/nyc_trees/apps/users/tests.py
src/nyc_trees/apps/users/views/group.py

This tests the workflow of attaining mapper status and also fixes a few subtle bugs.

Add unit tests for trusted mapper and individual mapper status workflows

---

src/nyc_trees/apps/survey/templates/survey/reservations.html
src/nyc_trees/apps/survey/views.py

We mentioned this enough times that it ought to be done (even if this page ends up getting remodeled).

Zoom to reservations

---

src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/js/src/lib/SelectableBlockfaceLayer.js
src/nyc_trees/js/src/lib/mapUtil.js
src/nyc_trees/js/src/surveyPage.js

Add UI for blockface endpoint selection on survey page

---

src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/apps/survey/views.py

Accessing the survey page as an individual mapper will set the map
bounds to the extent of your reservations.

Set survey bounds to reservations extent

---

src/nyc_trees/js/src/lib/mapUtil.js
src/nyc_trees/js/src/reservationPage.js
src/nyc_trees/js/src/surveyPage.js

When clicking on a blockface on the Reservation and Survey pages, the
map will immediately pan and zoom to the target blockface.

Zoom to blockface onclick

---

src/nyc_trees/apps/home/templates/home/quiz_complete_page.html
src/nyc_trees/apps/home/training/views.py

How to test:
1. Complete the training quiz
2. The quiz results page should display the answers you selected and whether or not they are correct.

Show submitted questions/answers summary after completing a quiz

---

src/nyc_trees/apps/users/templates/users/partials/profile/achievements.html

Achievements on user profile should not link to anything

---

src/nyc_trees/js/src/searchController.js

Fixes #307 ...again.
Not a priority for sprint review.

Disable Leaflet click propagation on search control

---

src/nyc_trees/js/src/map.js

More muted than Toner, which should make it easier to see and interact with the blockfaces.
http://cartodb.com/basemaps/
Fixes #652

Switch to CartoDB positron base map

---

src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html
src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/apps/survey/views.py
src/nyc_trees/js/src/surveyPage.js

Also fixes a few bugs with the treecorder markup

Add code for submitting treecorder surveys

---

src/nyc_trees/apps/event/templates/event/partials/event_section.html
src/nyc_trees/apps/users/templates/users/partials/event_email_opt_in.html

Fix styling for User Settings > Emails

---

src/nyc_trees/sass/partials/_header.scss
src/nyc_trees/sass/partials/_variables.scss

Increase header z-index to appear over leaflet attribution

---

src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/js/src/surveyPage.js

Make "No Trees" button on the survey functional and add "Map Another?" modal

---

src/nyc_trees/sass/partials/_typography.scss
src/nyc_trees/templates/registration/activation_complete.html
src/nyc_trees/templates/registration/registration_form.html

- Adds bootstrap checkbox class around checkbox and label pairs
- Appropriately styles list
- Fixes #561

Style checkboxes on registration

---

src/nyc_trees/apps/survey/templates/survey/reservations_instructions.html
src/nyc_trees/apps/survey/views.py

This adds some logic to make steps inactive until you are able to start
that step.
I figured out a simpler way to accomplish this after giving it some thought. Please test to see if this behavior works as expected.

Update reservations instructions view

---

src/nyc_trees/apps/survey/templates/survey/reservations_instructions.html
src/nyc_trees/apps/survey/views.py

Style reservations instructions page

---

src/nyc_trees/js/src/map.js
src/nyc_trees/js/src/surveyDetail.js

Add sattelite basemap to survey detail page

---

src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html
src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/apps/survey/templates/survey/survey_detail.html
src/nyc_trees/sass/partials/_globals.scss
src/nyc_trees/sass/partials/_map.scss
src/nyc_trees/sass/partials/_survey.scss

Style treecorder confirmation page

---

deployment/MIGRATIONS.md

This update to the migrations documentation includes steps for disabling and enabling deployments before and after applying migrations.

Update migration documentation to including automated deployment

---

src/nyc_trees/sass/partials/_globals.scss

Override default plugin style

---

src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html
src/nyc_trees/sass/partials/_survey.scss

This will update the look of select2 dropdowns to match the theme.

style changes for select2 to match bootstrap styling

---

scripts/check.sh
scripts/debugserver.sh
scripts/manage.sh
scripts/npm.sh
scripts/test.sh

For parsing with third-party script execution tools

Add docstring comments to popular scripts

---

src/nyc_trees/js/src/surveyPage.js

Disable map activity during survey form

---

src/nyc_trees/js/src/surveyPage.js

Needed for better UX on mobile devices with soft keyboards

Blur the Select2 element when it is closed.

---

src/nyc_trees/apps/core/migrations/0017_group_affiliation.py
src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/users/forms.py
src/nyc_trees/apps/users/templates/groups/list.html
src/nyc_trees/apps/users/templates/groups/settings.html
src/nyc_trees/js/src/group_list.js

Add group affiliation field and use it for searching on groups page

---

src/nyc_trees/js/src/surveyPage.js

Show custom validation message for problems checkbox group

---

src/nyc_trees/apps/users/templates/groups/detail.html
src/nyc_trees/sass/partials/_globals.scss

changed the layout of group image and name to fix text clipping

---

src/nyc_trees/apps/survey/templates/survey/partials/map_another_popup.html
src/nyc_trees/apps/survey/views.py
src/nyc_trees/js/src/mapAnotherPopup.js
src/nyc_trees/js/src/surveyPage.js

fixes #802
Only show map another block prompt when there are remaining reservations.

Limit map another block prompt

---

src/nyc_trees/apps/core/templates/base.html
src/nyc_trees/templates/registration/login.html

Redirect to previous page when clicking on the login link.

---

src/nyc_trees/apps/geocode/views.py

Return a 400 error if there is a request to geocode without an address

---

src/nyc_trees/libs/custom_storages.py
src/nyc_trees/nyc_trees/settings/production.py

Add custom Django storage backend to work around boto issue

---

src/nyc_trees/apps/core/management/commands/start_daily_celery_task.py
src/nyc_trees/apps/core/migrations/0019_auto_20150319_1136.py
src/nyc_trees/apps/core/models.py

Uses DB locking via `select_for_update` to ensure that the task is only
started once per day.
To test, run migrations, and then run the following command at the same
time in two separate shells:
'manage.py start_daily_celery_task debug_task'
The task should only be triggered once, which can be verified by looking
in the Celery logs.

Add a management command for starting a scheduled Celery task

---

src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html
src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/sass/partials/_survey.scss

cant map block button moved - fix #881. No trees button adjusted - fix #877

---

src/nyc_trees/apps/core/management/commands/start_daily_celery_task.py

Row-level locking is not adequate to ensure that only a single task is
queued, since we add new rows for each task.
This is fixed by acquiring an exclusive lock on the entire table,
rather than a subset of row.

Fix locking of DB for starting Celery tasks

---

src/nyc_trees/js/src/surveyPage.js

We were failing to serialize fields for collapsed tree sections properly,
causing server-side errors when submitting the survey.
While fixing this, I also found and fixed another related bug, where
form elements where disabled prior to validation, but were not properly
re-enabled after validation had completed, which was also caused by the
the tree sections being collapsed.
Fixes #840 and Fixes #883.

Fix treecorder survey submission when tree sections are collapsed.

---

src/nyc_trees/apps/event/templates/event/event_list_page.html
src/nyc_trees/apps/event/templates/event/partials/rsvp.html
src/nyc_trees/apps/home/templates/home/partials/home_public.html
src/nyc_trees/apps/survey/templates/survey/blockface_cart.html
src/nyc_trees/apps/survey/templates/survey/reservations.html
src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html
src/nyc_trees/apps/survey/templates/survey/reserve_blockface_confirmation.html
src/nyc_trees/apps/users/templates/groups/list.html
src/nyc_trees/apps/users/templates/users/partials/privacy_controls.html
src/nyc_trees/apps/users/templates/users/settings.html
src/nyc_trees/sass/partials/_buttons.scss

The text was provided by Parks.
The one adjustment I made to the sass was to compensate for the word
"Attending" being a longer than "RSVPed"
Fixes #848

Update page copy

---

src/nyc_trees/apps/core/migrations/0020_auto_20150323_1457.py
src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/event/migrations/0009_event_map_pdf_filename.py
src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/event/templates/event/printable_event_map.html
src/nyc_trees/apps/event/views.py
src/nyc_trees/apps/survey/templates/survey/printable_reservations_map.html
src/nyc_trees/apps/survey/views.py
src/nyc_trees/apps/users/views/group.py
src/nyc_trees/js/backend/url2pdf.js
src/nyc_trees/js/src/map.js
src/nyc_trees/js/src/printableEventMapPage.js
src/nyc_trees/js/src/printableReservationsMapPage.js
src/nyc_trees/libs/pdf_maps.py
src/nyc_trees/libs/phantomjs.py
src/nyc_trees/nyc_trees/__init__.py
src/nyc_trees/sass/partials/_map.scss

Generate PDF maps for events and for user reservations using PhantomJS.
In order to unblock dependencies I'm leaving as a TODO:
Add PhantomJS resource timeout and celery retry logic.

Generate PDF maps for events 

---

src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/core/templates/core/partials/polling_download_section.html
src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/event/templates/event/event_detail.html
src/nyc_trees/apps/survey/routes.py
src/nyc_trees/apps/survey/urls/blockface.py
src/nyc_trees/apps/survey/views.py
src/nyc_trees/apps/users/__init__.py
src/nyc_trees/apps/users/templates/users/partials/profile/reservations.html
src/nyc_trees/js/backend/url2pdf.js
src/nyc_trees/js/src/event.js
src/nyc_trees/js/src/home.js
src/nyc_trees/js/src/lib/pollForDownload.js
src/nyc_trees/js/src/userProfile.js
src/nyc_trees/libs/pdf_maps.py

* Factor out polling for downloads: template, JavaScript, Python
* If reservations exist, poll for reservations map PDFs on profile and dashboard
* Generate new map on poll if reservation IDs have changed
Fixes #859

Download button for reservations map PDFs, with polling

---

deployment/ansible/roles/nyc-trees.app/defaults/main.yml
deployment/ansible/roles/nyc-trees.app/tasks/cron.yml
deployment/ansible/roles/nyc-trees.app/tasks/log-rotation.yml
deployment/ansible/roles/nyc-trees.app/tasks/main.yml
deployment/ansible/roles/nyc-trees.app/templates/logrotate-nyc-trees-cron.j2
deployment/ansible/roles/nyc-trees.beaver/templates/django.conf.j2
src/nyc_trees/apps/survey/management/commands/send_reminder_emails.py

This adds a cron job that successfully runs this task *every minute*, which is useful for debugging purpose. It will be switched to daily in the early AM before merging.
Opening this PR to open discussion, I have some questions.

Add cron job for reservation reminder task

---

src/nyc_trees/libs/pdf_maps.py

Fix phantomjs SSL error

---

src/nyc_trees/apps/mail/__init__.py
src/nyc_trees/apps/mail/libs.py
src/nyc_trees/apps/mail/tasks.py
src/nyc_trees/apps/mail/templates/mail/new_reservations_confirmed.txt
src/nyc_trees/apps/mail/templates/mail/new_reservations_confirmed_subject.txt
src/nyc_trees/apps/mail/views.py
src/nyc_trees/apps/survey/views.py
src/nyc_trees/libs/pdf_maps.py

Send Email when blockfaces are reserved

---

src/nyc_trees/apps/core/models.py

Case-insensitive logins

---

src/nyc_trees/apps/home/templates/home/partials/dashboard.html
src/nyc_trees/apps/home/templates/home/partials/home_public.html

Remove 'show me the map' link

---

src/nyc_trees/apps/login/templates/login/forgot_username_email.txt
src/nyc_trees/apps/mail/templates/mail/base_email.txt
src/nyc_trees/apps/mail/templates/mail/group_mapping_approved.txt
src/nyc_trees/apps/mail/templates/mail/new_reservations_confirmed.txt
src/nyc_trees/apps/mail/templates/mail/reservation_reminder.txt
src/nyc_trees/apps/mail/templates/mail/rsvp.txt
src/nyc_trees/templates/registration/activation_email.txt
src/nyc_trees/templates/registration/password_reset_email.html

Add footer with link to help email address to every email.

---

src/nyc_trees/apps/core/templates/core/partials/nav.html
src/nyc_trees/apps/home/routes.py
src/nyc_trees/apps/home/templates/home/about_faq.html
src/nyc_trees/apps/home/urls.py
src/nyc_trees/apps/home/views.py
src/nyc_trees/nyc_trees/settings/base.py

Add About & FAQ page

---

src/nyc_trees/apps/event/forms.py
src/nyc_trees/apps/event/templates/event/partials/event_form.html
src/nyc_trees/js/src/event_map.js
src/nyc_trees/js/src/searchController.js
src/nyc_trees/sass/partials/_events.scss

If you press "enter" with the address field focused, or click the
search button, the small map will move to the geocoded address.
Fixes #949

Add geocoder to add event page

---

src/nyc_trees/apps/core/templates/core/partials/nav.html

Set sidebar link hrefs

---

src/nyc_trees/apps/home/templates/home/partials/home_public.html

[We may get logos before the launch]
Fixes #1006

Hide sponsors until logos are available

---

src/nyc_trees/nyc_trees/settings/base.py

Lower blockface reservation limit to 12

---

src/nyc_trees/sass/partials/_events.scss

styled the resuts of the geocoder list

---

src/nyc_trees/apps/core/templates/base_two_frames.html
src/nyc_trees/sass/partials/_globals.scss

Set up two column layout on desktop

---

src/nyc_trees/templates/registration/password_reset_form.html

Load templatetag library for 'add_class'

---

src/nyc_trees/apps/users/templates/groups/detail.html

Add affiliation to group detail page

---

src/nyc_trees/apps/home/templates/home/individual_mapper_instructions.html

styled the individual mapper status success page

---

src/nyc_trees/apps/core/templates/base_event.html
src/nyc_trees/apps/core/templates/base_two_frames.html
src/nyc_trees/apps/home/templates/home/partials/home_public.html
src/nyc_trees/sass/partials/_globals.scss
src/nyc_trees/sass/partials/_map.scss

03591ef870d76f70f6a516d845ae0e528b85e2df

Begin styling for tablet sized devices

---

src/nyc_trees/apps/home/templates/home/partials/legend.html
src/nyc_trees/apps/survey/templates/survey/partials/progress_legend.html
src/nyc_trees/apps/survey/templates/survey/partials/reservations_legend.html
src/nyc_trees/apps/survey/templates/survey/progress.html
src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html
src/nyc_trees/sass/partials/_map.scss

Fixes #368. Previously, this text was hidden on mobile screen sizes.

Show legend text on modal

---

src/nyc_trees/apps/survey/management/commands/send_reminder_emails.py

@jwalgran @hectcastro @maurizi what do you think of this technique?
things of note:
- I added 1/2 second sleeping to stay under request limits. This is irrespective of retries - we should do this anyway
- I gave each email 4 attempts to send. It'll loop through the list of emails over and over until they've all succeeded or tried 4 times.
- It's going to be really hard to verify that this works in production.
- Because this isn't using celery, I didn't add it in just for retries. If this command was using celery, I would've gone that route. I'm not opposed to it now.

Try to send emails multiple times before failing 

---

src/nyc_trees/apps/survey/templates/survey/blockface_cart.html
src/nyc_trees/apps/survey/templates/survey/partials/progress_page_blockface_popup.html
src/nyc_trees/apps/survey/templates/survey/partials/reservations_legend.html
src/nyc_trees/apps/survey/templates/survey/partials/reserve_blockface_modals.html
src/nyc_trees/apps/survey/templates/survey/reservations.html
src/nyc_trees/apps/survey/templates/survey/reserve_blockface_confirmation.html
src/nyc_trees/apps/survey/templates/survey/survey.html

All user-visible "block faces" and "blockfaces" and "block sides" have become "block edges".
Fixes #1076.

Change all variations to block edges

---

deployment/deployment-helper.sh
deployment/requirements.txt
deployment/troposphere/template_utils.py

This AMI listing directories contains the officially released Ubuntu Cloud Images.
See also: http://cloud-images.ubuntu.com/releases/14.04/release/

Use currently released Ubuntu AMI listing

---

src/nyc_trees/apps/survey/fixtures/species.json

Parks provided us with a new species CSV. I formatted the columns to match our existing schema, and then used [csv2json.py](https://djangosnippets.org/snippets/1680/) to convert it to a Django fixture.
Connects to #1098

Update species fixture

---

src/nyc_trees/apps/event/templates/event/partials/event_section.html
src/nyc_trees/apps/users/templates/groups/partials/event_section.html
src/nyc_trees/apps/users/templates/users/partials/event_email_opt_in.html
src/nyc_trees/sass/partials/_events.scss
src/nyc_trees/sass/partials/_globals.scss

Add icons on all event partials

---

src/nyc_trees/apps/core/templates/core/partials/polling_download_section.html
src/nyc_trees/apps/home/templates/home/partials/dashboard.html
src/nyc_trees/apps/home/templates/home/partials/home_public.html
src/nyc_trees/apps/home/templates/home/partials/ticker.html
src/nyc_trees/apps/users/templates/users/partials/activity.html
src/nyc_trees/apps/users/templates/users/partials/profile/groups.html
src/nyc_trees/apps/users/templates/users/partials/profile/reservations.html
src/nyc_trees/sass/partials/_events.scss
src/nyc_trees/sass/partials/_globals.scss
src/nyc_trees/sass/partials/_home.scss

Restyle desktop dashboard

---

src/nyc_trees/apps/core/templates/skeleton.html

Add page title

---

src/nyc_trees/apps/home/templates/home/partials/dashboard.html
src/nyc_trees/apps/home/templates/home/partials/species_modal.html
src/nyc_trees/libs/sql.py
src/nyc_trees/sass/partials/_home.scss

Sort species modal by tree count and add scrolling.

---

src/nyc_trees/apps/mail/templates/mail/new_reservations_confirmed.txt
src/nyc_trees/apps/mail/templates/mail/new_reservations_confirmed_subject.txt
src/nyc_trees/apps/mail/templates/mail/reservation_reminder.txt
src/nyc_trees/apps/mail/templates/mail/reservation_reminder_subject.txt
src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html
src/nyc_trees/apps/survey/templates/survey/reserve_blockface_confirmation.html
src/nyc_trees/apps/survey/urls/blockface.py
src/nyc_trees/apps/survey/urls/census_admin.py
src/nyc_trees/apps/survey/urls/survey.py
src/nyc_trees/apps/survey/views.py
src/nyc_trees/js/src/adminTerritoryPage.js
src/nyc_trees/js/src/lib/mapUtil.js
src/nyc_trees/js/src/progressPage.js
src/nyc_trees/js/src/reserveBlockfacePage.js
src/nyc_trees/js/src/surveyDetail.js
src/nyc_trees/nyc_trees/urls.py

Change blockface to blockedge in URLs and text
Fixes #1042

Blockface to blockedge

---

src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/survey/models.py

Add default ordering for several models.

---

src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/core/test_utils.py
src/nyc_trees/apps/users/__init__.py
src/nyc_trees/apps/users/models.py
src/nyc_trees/apps/users/templates/users/partials/profile/achievements.html
src/nyc_trees/apps/users/tests.py

* Create achievement definitions per #1058
* `update_achievements()` creates `Achievement` objects for specified user
* Test each kind of achievement
Also create helpers `complete_online_training` and `blocks_mapped_count`
Fixes #1058

Add achievement definitions

---

src/nyc_trees/apps/core/migrations/0022_auto_20150414_1228.py
src/nyc_trees/apps/event/migrations/0010_auto_20150414_1228.py
src/nyc_trees/apps/survey/migrations/0015_auto_20150414_1228.py
src/nyc_trees/apps/users/migrations/0005_auto_20150414_1228.py

I could not run ``migrate`` on the develop branch because it reported that there were changes to the models not reflected in the migrations. I ran ``manage.py makemigrations`` and added all the generated migrations.

Add missing migrations

---

src/nyc_trees/apps/core/templates/base.html
src/nyc_trees/apps/core/templates/core/partials/nav.html
src/nyc_trees/sass/partials/_footer.scss

Show styled footer on desktop

---

src/nyc_trees/apps/census_admin/tasks.py
src/nyc_trees/apps/core/management/commands/dump_db.py

Dump events table as shapefile instead of CSV.

---

src/nyc_trees/apps/event/templates/event/partials/event_form.html
src/nyc_trees/sass/partials/_events.scss

styled time fields for event creation and editing

---

src/nyc_trees/apps/core/templates/core/partials/nav.html
src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/event/templates/event/event_detail.html
src/nyc_trees/apps/event/tests.py
src/nyc_trees/nyc_trees/context_processors.py

Show "Start Mapping" button for events in-progress

---

src/nyc_trees/js/src/copyEventUrl.js

Update "Copy URL" prompt text

---

src/nyc_trees/apps/core/admin.py
src/nyc_trees/apps/core/migrations/0023_group_border.py
src/nyc_trees/apps/core/models.py

Add border to group model, enable editing of it in the Django Admin

---

src/nyc_trees/apps/home/static/flatpages/getting_started.html
src/nyc_trees/apps/home/static/flatpages/the_mapping_method.html
src/nyc_trees/apps/home/static/flatpages/tree_data.html
src/nyc_trees/apps/home/static/flatpages/tree_surroundings.html

This text was manually edited and updated by @dboyer on the staging
server, so this commit brings the latest correct text into version control.

Update training text

---

src/nyc_trees/apps/core/templates/core/partials/nav.html
src/nyc_trees/apps/users/__init__.py
src/nyc_trees/apps/users/templates/users/achievement.html
src/nyc_trees/apps/users/templates/users/partials/achievement.html
src/nyc_trees/apps/users/templates/users/partials/profile/achievements.html
src/nyc_trees/apps/users/tests.py
src/nyc_trees/apps/users/views/user.py

Add achievements page, link to it from user profile and nav bar

---

src/nyc_trees/apps/users/templates/groups/list.html

Remove register group button. Fixes #1197

---

src/nyc_trees/sass/partials/_events.scss

Fix calendar proportions

---

src/nyc_trees/apps/core/templates/base_reservation.html
src/nyc_trees/apps/core/templates/base_survey.html
src/nyc_trees/apps/users/templates/groups/list.html
src/nyc_trees/sass/partials/_map.scss

made heading spacing more consistent accross pages

---

src/nyc_trees/apps/core/migrations/0024_auto_20150416_1136.py
src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/survey/helpers.py
src/nyc_trees/apps/survey/routes.py
src/nyc_trees/apps/survey/templates/survey/partials/group_popup.html
src/nyc_trees/apps/survey/templates/survey/progress.html
src/nyc_trees/apps/survey/urls/blockface.py
src/nyc_trees/apps/survey/views.py
src/nyc_trees/apps/users/tests.py
src/nyc_trees/apps/users/views/group.py
src/nyc_trees/js/src/progressPage.js

When a group polygon is clicked, loads the group's blockfaces and loads
a popup with group info into the action bar
Fixes #970

Add groups mode on progress page

---

src/nyc_trees/apps/mail/libs.py
src/nyc_trees/apps/mail/templates/mail/rsvp.txt

Update event registration email text

---

src/nyc_trees/sass/partials/_map.scss

prefixed the transforms for reservation-action-items for iphone

---

src/nyc_trees/apps/home/templates/home/partials/training.html
src/nyc_trees/apps/home/templates/home/training.html
src/nyc_trees/apps/home/tests.py
src/nyc_trees/apps/home/training/types.py
src/nyc_trees/apps/home/training/views.py
src/nyc_trees/apps/home/views.py

fixes #589 on github
finished, in progress, not started, not logged in
here's how this will look.
First you come as an anonymous user:
then you log in:
then you start online training:
then you finish:

Update training material for four users states

---

src/nyc_trees/apps/core/templates/core/partials/nav.html

Don't show the privacy button in the nav if the user is a minor

---

src/nyc_trees/apps/survey/templates/survey/partials/progress_legend.html

Properly structure paragraphs

---

src/nyc_trees/sass/partials/_legend.scss

Add 'in your cart' legend color

---

src/nyc_trees/apps/event/templates/event/partials/event_form.html
src/nyc_trees/apps/event/views.py

Use location data from form, not event object.

---

src/nyc_trees/sass/partials/_home.scss

Make dashboard circles clickable on mobile

---

src/nyc_trees/sass/partials/_legend.scss
src/tiler/style/progress.mss

Change unmapped color to brown

---

src/nyc_trees/sass/partials/_events.scss

uniform menu button styles on group events page

---

src/nyc_trees/apps/home/views.py

Show 1 decimal place in % complete if < 10%

---

src/nyc_trees/apps/survey/templates/survey/progress.html

Comment-out "My Progress" option on progress page drop-down

---

src/nyc_trees/apps/users/views/group.py

Set group page event list default length to 3

---

src/nyc_trees/apps/home/templates/home/partials/training.html
src/nyc_trees/apps/home/training/__init__.py
src/nyc_trees/apps/home/training/types.py

Remove training times from training page

---

src/nyc_trees/sass/partials/_header.scss

fixed scrollbar overlap on navbar

---

src/nyc_trees/apps/users/templates/groups/detail.html
src/nyc_trees/apps/users/tests.py
src/nyc_trees/apps/users/views/group.py
src/nyc_trees/sass/partials/_home.scss

Change group tree count from circle to ticker.

---

src/nyc_trees/apps/event/templates/event/event_list_page.html

Add Events page content

---

src/nyc_trees/apps/event/forms.py
src/nyc_trees/apps/event/migrations/0011_auto_20150420_1543.py
src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/event/views.py
src/nyc_trees/apps/users/tests.py

Cleanup event title and slug validation

---

src/nyc_trees/apps/mail/tasks.py
src/nyc_trees/apps/mail/templates/mail/group_mapping_approved.txt
src/nyc_trees/apps/mail/templates/mail/group_mapping_approved_subject.txt
src/nyc_trees/apps/mail/templates/mail/new_reservations_confirmed.txt
src/nyc_trees/apps/mail/templates/mail/new_reservations_confirmed_subject.txt
src/nyc_trees/apps/mail/templates/mail/reservation_reminder.txt
src/nyc_trees/apps/mail/templates/mail/reservation_reminder_subject.txt
src/nyc_trees/apps/mail/views.py
src/nyc_trees/apps/survey/views.py

Fixes #1051
Fixes #1052
Fixes #1053

Update email text content

---

src/nyc_trees/apps/home/templates/home/partials/training.html

Make training text the same for anon and new users

---

src/nyc_trees/nyc_trees/settings/base.py

Change reservation expiration from 14 days to 7 days

---

src/nyc_trees/apps/census_admin/templates/census_admin/upload_group_polygons.html
src/nyc_trees/apps/census_admin/views.py
src/nyc_trees/apps/survey/templates/survey/admin_territory.html
src/nyc_trees/apps/survey/urls/census_admin.py
src/nyc_trees/apps/survey/views.py
src/nyc_trees/js/src/lib/SelectableBlockfaceLayer.js
src/nyc_trees/sass/partials/_legend.scss

Fixes #1307 
Fixes #1297 
Fixes #1298

Updates to census admin pages

---

src/nyc_trees/apps/survey/views.py

Fix error when cancelling single blockface

---

src/nyc_trees/apps/survey/layer_context.py

Catch exception when Group does not exist in layer_context.py

---

src/nyc_trees/apps/users/views/group.py

Show private events on group admin tab

---

src/nyc_trees/apps/home/templates/home/partials/dashboard.html
src/nyc_trees/apps/users/templates/users/partials/activity.html
src/nyc_trees/apps/users/templates/users/partials/profile/achievements.html
src/nyc_trees/apps/users/templates/users/partials/profile/section.html

Removes collapse functionality. Fixes #1327.

Add urls on dashboard headings

---

src/nyc_trees/js/src/trainingFlatpage.js

Make sure to show images when restoring exercise

---

src/nyc_trees/js/src/event_list_page.js

Show blank event map when there are no future events

---

src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html
src/nyc_trees/js/src/reserveBlockfacePage.js

Fix static action bar on reservation page

---

src/nyc_trees/js/src/lib/tabhash.js

Change tabs on browser back/forward to match hash

---

src/nyc_trees/apps/survey/migrations/0018_auto_20150422_1214.py
src/nyc_trees/apps/survey/models.py
src/nyc_trees/apps/survey/views.py

Add index to blockface updated_at cache buster field

---

src/nyc_trees/sass/partials/_globals.scss

Style unearned badges

---

src/nyc_trees/apps/home/templates/home/about_faq.html

Add FAQ text

---

src/nyc_trees/apps/home/templates/home/home.html
src/nyc_trees/apps/users/__init__.py
src/nyc_trees/apps/users/models.py
src/nyc_trees/apps/users/templates/users/achievement.html
src/nyc_trees/apps/users/templates/users/partials/achievement.html
src/nyc_trees/apps/users/templates/users/partials/achievement_modal.html
src/nyc_trees/apps/users/templates/users/partials/profile/achievements.html
src/nyc_trees/apps/users/templates/users/profile.html
src/nyc_trees/sass/partials/_globals.scss

Add text, sponsor and reward information to achievements page.

---

src/nyc_trees/apps/users/migrations/0006_auto_20150422_1649.py

Reopening to merge into develop

Add missing migration

---

src/nyc_trees/apps/survey/views.py

Check if user is authenticated when getting progress popup

---

src/nyc_trees/apps/event/templates/event/event_list_page.html
src/nyc_trees/apps/home/templates/home/partials/dashboard.html

To be consistent with the rest of the site, or the nearby text.
Fixes #1400
Fixes #1402

Text adjustments

---

src/nyc_trees/apps/home/templates/home/partials/training.html

To make it easier to review the training materials while answering the check-in questions and the quiz.
Fixes #1393

Open training PDF in new tab or window

---

src/nyc_trees/apps/login/templates/login/send_activation_email.html

Fix typo in activation email template

---

src/nyc_trees/apps/home/templates/home/partials/home_public.html

Update sponsor heading and order on home page

---

src/nyc_trees/templates/registration/password_reset_confirm.html

Style password reset button.

---

src/nyc_trees/libs/sql.py

This had already been done for the dashboard, but the public homepage was missed.
Not sure if this should be against develop or the release branch.
Fixes #1102

Sort species modal by tree count for on public home page

---

src/nyc_trees/templates/registration/registration_complete.html

Remove italic and add bold

---

src/nyc_trees/apps/users/models.py
src/nyc_trees/apps/users/templates/users/partials/achievement.html

Update achievement detail text

---

src/nyc_trees/sass/partials/_home.scss

Increase size of hero image

---

src/nyc_trees/apps/users/templates/groups/detail.html

Group websites open in new tab

---

src/nyc_trees/apps/users/__init__.py
src/nyc_trees/apps/users/routes/user.py
src/nyc_trees/apps/users/templates/users/achievement.html
src/nyc_trees/apps/users/views/user.py

Fixes #1435 
I coordinated with @jfrankl on the header text / design.

Allow anonymous users to access the achievements page.

---

src/nyc_trees/sass/partials/_globals.scss

Remove outline on tab click

---

src/nyc_trees/sass/partials/_header.scss
src/nyc_trees/sass/partials/_survey.scss

fixed map control z-indexes

---

src/nyc_trees/apps/home/templates/home/training_instructions.html
src/nyc_trees/apps/survey/templates/survey/reservations_instructions.html

* "Mapping event" instead of "second training event"
* "Training event" instead of "first training event"
Fixes #1442

Change language for training/mapping events

---

deployment/ansible/roles/nyc-trees.app/tasks/cron.yml

s/db_dump/dump_db/
Attempts to resolve #1456.

Fix cron task entry for daily database dump

---

src/nyc_trees/js/src/map.js

Set maximum zoom on all maps

---

src/nyc_trees/js/src/map.js

Mistakenly left this out of my previous PR.

Also set min zoom

---

src/nyc_trees/apps/event/migrations/0012_auto_20150424_1705.py
src/nyc_trees/apps/event/views.py

* Data migration to clear all event PDF references
* When viewing event page, create PDF if it's missing
Fixes #1429

Re-create event PDFs

---

src/nyc_trees/apps/survey/layer_context.py
src/nyc_trees/apps/survey/views.py
src/nyc_trees/js/src/progressPage.js
src/tiler/server.js
src/tiler/sql/group_progress.sql
src/tiler/sql/progress.sql
src/tiler/sql/user_progress.sql

This was part of #1313, I am pulling it out because it is a smaller simpler change with less risk involved

Remove unecessary join to Territory table from progress layer queries

---

src/nyc_trees/apps/home/training/quiz_strings.py

Passing the quiz allows you to RSVP for training events. An untrained user can follow groups any time.

Update quiz header text

---

src/nyc_trees/apps/survey/helpers.py
src/nyc_trees/apps/survey/views.py

Allow any active user to be selected as a teammate

---

src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/survey/tests.py
src/nyc_trees/apps/survey/views.py
src/nyc_trees/libs/sql.py
src/tiler/sql/user_progress.sql

Give teammates credit for achievements, user profile contributions, and for "My Progress" on the progress page.
Fixes #1432

Give teammates credit on profile, achievements, and progress page

---

src/nyc_trees/apps/core/templates/404.html

Style 404 page

---

src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/js/shim/leaflet.utfgrid-src.js
src/nyc_trees/js/src/adminTerritoryPage.js
src/nyc_trees/js/src/lib/mapUtil.js
src/nyc_trees/js/src/map.js
src/nyc_trees/js/src/progressPage.js
src/nyc_trees/js/src/surveyPage.js
src/nyc_trees/sass/partials/_map.scss
src/tiler/server.js
src/tiler/sql/group_territory_survey.sql
src/tiler/sql/user_reservations.sql

Treecorder crosshairs

---

src/nyc_trees/apps/survey/admin.py

Don't load all blockfaces to an admin site dropdown

---

src/nyc_trees/sass/partials/_globals.scss

Fixes #1477. The issue is that we're not using glyphicons on this project. I added css triangles in place of the glyphicon arrows.

Add arrows on timepicker ui

---

src/nyc_trees/sass/partials/_survey.scss

This will make select2 a bit easier to use when on tablets

expand select2 dropdown full height for tablet size and down

---

src/nyc_trees/js/src/surveyPage.js

Focus on first input field when adding a new tree in treecorder.

---

src/nyc_trees/apps/users/templates/groups/detail.html

Fix group attendees count on group detail page.

---

src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html
src/nyc_trees/js/src/surveyPage.js

Hide other problems sections when "No Problems" is selected.

---

src/nyc_trees/apps/survey/management/commands/send_reminder_emails.py

Don't send reminder email for expires reservations

---

src/nyc_trees/js/src/surveyPage.js

Fix bug with form elements being disabled during validation.

---

src/nyc_trees/js/src/lib/mapUtil.js
src/nyc_trees/js/src/reserveBlockfacePage.js
src/nyc_trees/npm-shrinkwrap.json
src/nyc_trees/package.json

Zoom to and preselect blockface on reservations page based on hash
Used on the dashboard to deeplink to reservations.
Connects to #1224

Zoom to deep linked block on reservations

---

src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/event/templates/event/partials/rsvp.html
src/nyc_trees/apps/event/views.py
src/nyc_trees/apps/users/templates/groups/partials/event_section.html

Disallow actions on past events

---

src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/js/src/surveyPage.js

Add address search to survey map

---

src/nyc_trees/gulpfile.js

Fix race condition with gulp watch and sass

---

src/nyc_trees/apps/mail/tasks.py
src/nyc_trees/apps/mail/templates/mail/new_reservations_confirmed.txt

Add email text for paper reservation confirmation

---

src/nyc_trees/sass/partials/_survey.scss

added max-width to select2 dropdown on tablet on down

---

src/nyc_trees/apps/core/templates/base_reservation.html
src/nyc_trees/apps/survey/templates/survey/progress.html
src/nyc_trees/sass/partials/_map.scss

Show actionbar on progress map when someone interacts with map

---

src/nyc_trees/apps/core/admin.py
src/nyc_trees/apps/core/migrations/0028_user_survey_geolocate_help_shown.py
src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/event/templates/event/admin_checkin.html
src/nyc_trees/apps/event/templates/event/event_detail.html
src/nyc_trees/apps/event/templates/event/printable_event_map.html
src/nyc_trees/apps/event/views.py
src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/apps/survey/views.py
src/nyc_trees/js/src/event.js
src/nyc_trees/js/src/map.js
src/nyc_trees/js/src/printableEventMapPage.js
src/nyc_trees/js/src/surveyPage.js
src/nyc_trees/sass/partials/_map.scss

This adds a new option to the map to geolocate the user location on
page load.
Connects #1253

Zoom to user location on survey page

---

Vagrantfile
src/nyc_trees/apps/census_admin/tasks.py
src/nyc_trees/apps/census_admin/templates/census_admin/data_doc.html
src/nyc_trees/apps/core/management/commands/data_dict.py
src/nyc_trees/apps/core/management/commands/dump_db.py
src/nyc_trees/apps/core/migrations/0028_auto_20150505_1155.py
src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/event/migrations/0013_auto_20150505_1155.py
src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/survey/migrations/0020_auto_20150505_1155.py
src/nyc_trees/apps/survey/models.py
src/nyc_trees/apps/users/migrations/0007_auto_20150505_1155.py
src/nyc_trees/apps/users/models.py
src/nyc_trees/libs/mixins.py

Create data dictionary and include it in the data dump zip file

---

src/nyc_trees/apps/home/templates/home/partials/legend.html
src/nyc_trees/apps/users/templates/users/profile.html
src/nyc_trees/sass/partials/_globals.scss
src/nyc_trees/sass/partials/_map.scss

Fixes #1532. This was an issue with all modals it seems.

Fix issue where top of modal was off screen

---

src/nyc_trees/apps/survey/templates/survey/partials/tree_form.html

Hide tree size details until structure is chosen

---

src/nyc_trees/js/src/surveyPage.js

Use same logic for selecting blockface from hash as used for crosshairs

---

src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/js/src/surveyPage.js
src/nyc_trees/sass/partials/_survey.scss

added no further trees on block action for treecorder

---

src/nyc_trees/js/src/map.js

Use https for survey detail map.

---

src/nyc_trees/js/src/surveyPage.js

Add minimum input and placeholder text to species autocomplete

---

src/nyc_trees/sass/partials/_form-errors.scss

non form errors styled

---

src/nyc_trees/apps/home/templates/home/individual_mapper_instructions.html

content change to mapper status page

---

src/nyc_trees/apps/event/models.py
src/nyc_trees/apps/users/templates/groups/partials/event_section.html

Hide email attendees link after the event is more than one week old

---

src/nyc_trees/js/src/progressPage.js

We were attaching duplicate event handlers whenever the mode changed.
This caused two issues: we made duplicate AJAX calls after switching modes,
and we allowed clicking on blockfaces in group mode (which we shouldn't)
Connects to #1560

Fix event handling for selecting blockfaces on progress page.

---

src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/home/views.py
src/nyc_trees/apps/survey/helpers.py
src/nyc_trees/apps/survey/models.py
src/nyc_trees/apps/survey/tests.py
src/nyc_trees/libs/sql.py
src/tiler/sql/group_progress.sql
src/tiler/sql/progress.sql
src/tiler/sql/user_progress.sql

Only count completed surveys when determining progress and map styling

---

src/nyc_trees/apps/survey/admin.py

Add search by blockface to admin site

---

src/nyc_trees/apps/event/views.py
src/nyc_trees/apps/mail/__init__.py
src/nyc_trees/apps/mail/tasks.py
src/nyc_trees/apps/mail/templates/mail/after_event_checkin.txt
src/nyc_trees/apps/mail/templates/mail/after_event_checkin_subject.txt

connects to #1584 on github
Not sure if this is sufficient. If the user keeps clicking the check-toggle button - they're gonna send a *lot* of emails.

Send email after event checkin

---

src/nyc_trees/apps/survey/templates/survey/survey_detail.html
src/nyc_trees/sass/partials/_buttons.scss

rearranged button placement on survery confirmation

---

src/nyc_trees/apps/event/views.py

Change this query from a `create` to a `get_or_create` so that Django
does not bother inserting a new EventRegistration record (and possibly
raising an IntegrityError) if a record already exists.
**Note:** It seems like this error is a product of having load balanced app servers which is difficult to test on our local (non load balanced) dev instances. Since I'm not able to reproduce this error, I can't guarantee for sure that this actually resolves the issue.
Connects #1564

Prevent possible IntegrityError triggered by clicking RSVP button

---

LICENSE

Switch license to AGPL

---

src/nyc_trees/apps/home/templates/home/training_instructions.html

Update training instructions text

---

src/nyc_trees/apps/event/templates/event/admin_checkin.html
src/nyc_trees/apps/event/templates/event/email_rsvps.html
src/nyc_trees/apps/event/views.py

Prevent checking in users until an event is "starting soon".

---

LICENSE
src/nyc_trees/apps/survey/migrations/0022_auto_20150512_1016.py
src/nyc_trees/apps/survey/migrations/layoutBoxes.sql

Fixes crashes when trees extend beyond the end of the blockface polyline.
Based on top of #1614 
Connects to #838

Update layout boxes fn

---

src/nyc_trees/apps/survey/layer_context.py
src/nyc_trees/apps/survey/routes.py
src/nyc_trees/apps/survey/views.py

Improves performance by removing an unecessary JOIN to the territory table, and adds a last modified header for caching.
Connects to #1611.

Improve group geojson performance

---

src/nyc_trees/apps/survey/templates/survey/reserve_blockface.html
src/nyc_trees/js/src/reserveBlockfacePage.js

Reservations: don't generate map tiles at low zooms

---

src/nyc_trees/apps/mail/templates/mail/rsvp.txt

Show event end time in RSVP email

---

src/nyc_trees/apps/event/views.py

This adds the current user and group admin to the list of recipients
for bulk event emails.
Connect #241

Send a copy of bulk event emails to group admin

---

src/nyc_trees/apps/census_admin/tasks.py

Fixes the dump_db command, which was failing on the data dictionary step.
Connects to #1632

Add new blockface fields to data dictionary mapping.

---

src/nyc_trees/apps/survey/fixtures/species.json
src/nyc_trees/apps/survey/migrations/0025_auto_20150513_1343.py

Update species list

---

src/nyc_trees/apps/survey/views.py

Mark blockface unavailable when quit by user

---

src/nyc_trees/apps/census_admin/tasks.py
src/nyc_trees/apps/core/management/commands/dump_db.py

Don't include unnecessary CSV fields.

---

src/nyc_trees/apps/census_admin/tasks.py

Format date fields in CSV/Shapefile exports

---

src/nyc_trees/apps/event/templates/event/event_detail.html
src/nyc_trees/apps/users/templates/groups/detail.html

Make email address visible on group detail page

---

src/nyc_trees/nyc_trees/context_processors.py

Fixes a typo in this url reverse lookup.

Fix error when logging in as normal user

---

deployment/ansible/roles.txt

See also:
- https://github.com/azavea/ansible-nginx/pull/4
- https://bugs.launchpad.net/nginx/+bug/1450770

Fix Nginx bug in logrotate postrotate script

---

src/nyc_trees/apps/core/decorators.py
src/nyc_trees/apps/core/migrations/0031_auto_20150513_1536.py
src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/home/templates/home/home.html
src/nyc_trees/apps/home/templates/home/individual_mapper_instructions.html
src/nyc_trees/apps/home/templates/home/trusted_mapper_request_sent.html
src/nyc_trees/apps/survey/templates/survey/partials/progress_page_blockface_popup.html
src/nyc_trees/apps/survey/templates/survey/reservations_instructions.html
src/nyc_trees/apps/survey/tests.py
src/nyc_trees/apps/users/forms.py
src/nyc_trees/apps/users/templates/groups/detail.html
src/nyc_trees/apps/users/templates/users/partials/activity.html
src/nyc_trees/apps/users/tests.py
src/nyc_trees/apps/users/uitests.py

changed the wording from individual mapper to independent mapper

---

src/nyc_trees/apps/home/templates/home/partials/treecorder_modal.html
src/nyc_trees/apps/survey/templates/survey/survey.html

Connects to #1639
Connects to #1640

Change text in treecorder modals.

---

src/nyc_trees/apps/survey/migrations/0026_auto_20150514_1005.py

Removes the polygons from the fixture and adds a data migration to delete
them if they already exist.
Connects to #1636

Remove some neighborhood polygons.

---

src/nyc_trees/apps/home/training/views.py

Fix exception when anonymous user visits training instructions

---

src/nyc_trees/apps/core/models.py
src/nyc_trees/apps/event/routes.py
src/nyc_trees/apps/event/templates/event/email_rsvps.html
src/nyc_trees/apps/event/templates/event/event_email_unsubscribed.html
src/nyc_trees/apps/event/templates/event/invalid_token.html
src/nyc_trees/apps/event/urls/group.py
src/nyc_trees/apps/event/views.py
src/nyc_trees/apps/mail/libs.py
src/nyc_trees/apps/mail/templates/mail/event.txt
src/nyc_trees/apps/mail/templates/mail/event_subject.txt
src/nyc_trees/apps/users/templates/users/settings.html

Add unsubscribe link to event emails

---

src/nyc_trees/libs/boto_mailer.py

This fixes an exception that is raised when EMAIL_BOTO_CHECK_QUOTA is
set to True.
Connects #621

Fix failure when email quota checking is enabled

---

src/nyc_trees/apps/core/templates/base_survey.html
src/nyc_trees/js/src/lib/stickyTitles.js
src/nyc_trees/js/src/surveyPage.js
src/nyc_trees/sass/partials/_globals.scss
src/nyc_trees/sass/partials/_survey.scss

Fix scrolling glitch on Treecorder for iOS7

---

scripts/aws/setupdb.sh
src/nyc_trees/apps/survey/management/commands/insert_state_plane_projection.py

This projection is required for more accurate geometry construction.
Connects to #1684

Add state plane projection install to setupdb.sh

---

src/nyc_trees/apps/core/templates/base.html
src/nyc_trees/apps/core/templates/core/partials/nav.html

Show logout link in nav instead of header when logged in.
Connects #411

Move logout link to nav

---

scripts/aws/setupdb.sh
src/nyc_trees/apps/survey/management/commands/touch_blockface.py

Create management command to bust tiler cache

---

src/nyc_trees/apps/survey/views.py

Convert any floats into integers for circumference and diameter fields.

---

src/nyc_trees/apps/survey/views.py

This seems like more correct behaviour that will lead to better data
quality.
Connects to #1695

Round floats to the nearest integer instead in survey submission.

---

src/nyc_trees/js/src/surveyPage.js

Fix bug that prevented the "Problems" section from reappearing.

---

src/nyc_trees/apps/home/templates/home/about_faq.html
src/nyc_trees/apps/home/templates/home/partials/home_public.html
src/nyc_trees/templates/registration/registration_form.html

Update text on about/faq, home, and registration pages.

---

src/tiler/.jshintrc
src/tiler/healthCheck.js
src/tiler/npm-shrinkwrap.json
src/tiler/package.json

Prevent health check from setting HTTP response more than once per call.

---

src/nyc_trees/apps/home/templates/home/about_faq.html

Update independent mapper text in the FAQ

---

src/nyc_trees/apps/core/templates/core/partials/nav.html
src/nyc_trees/apps/event/urls/event.py
src/nyc_trees/apps/home/templates/home/about_faq.html
src/nyc_trees/apps/home/templates/home/partials/home_public.html
src/nyc_trees/apps/survey/templates/survey/partials/reservations_legend.html
src/nyc_trees/apps/survey/urls/blockface.py
src/nyc_trees/apps/users/models.py
src/nyc_trees/apps/users/templates/users/achievement.html
src/nyc_trees/apps/users/templates/users/partials/activity.html
src/nyc_trees/apps/users/templates/users/partials/profile/achievements.html
src/nyc_trees/apps/users/templates/users/partials/profile/reservations.html
src/nyc_trees/apps/users/urls/user.py
src/nyc_trees/nyc_trees/middleware.py

Text changes per Parks.

---

src/nyc_trees/apps/home/views.py

Always show one decimal place in dashboard progress percentage.

---

src/nyc_trees/apps/users/__init__.py
src/nyc_trees/apps/users/models.py
src/nyc_trees/apps/users/templates/users/achievement.html

Text tweaks

---

src/nyc_trees/apps/survey/management/commands/send_reminder_emails.py

Only send reservation reminders for current reservations

---

src/nyc_trees/apps/survey/admin.py
src/nyc_trees/apps/survey/migrations/0029_survey_submit_comment.py
src/nyc_trees/apps/survey/models.py
src/nyc_trees/apps/survey/templates/survey/survey_detail.html
src/nyc_trees/apps/survey/tests.py
src/nyc_trees/apps/survey/views.py
src/nyc_trees/js/src/surveyDetail.js

Add a comment field to indicate why a survey was flagged or restarted.

---

src/nyc_trees/js/src/reserveBlockfacePage.js

Show user location on the reservations page.

---

src/nyc_trees/nyc_trees/settings/base.py

Increase maximum number of reservations from 12 to 50

---

deployment/ansible/group_vars/all
deployment/ansible/roles/nyc-trees.app/tasks/dev-and-test-dependencies.yml
src/nyc_trees/apps/survey/templates/survey/progress.html

Remove "Groups" view from progress map

---

src/nyc_trees/apps/event/templates/event/event_list_page.html
src/nyc_trees/apps/home/templates/home/about_faq.html
src/nyc_trees/apps/home/templates/home/partials/dashboard.html
src/nyc_trees/apps/home/templates/home/partials/home_public.html
src/nyc_trees/apps/home/templates/home/partials/training.html
src/nyc_trees/apps/survey/templates/survey/partials/progress_legend.html
src/nyc_trees/apps/survey/templates/survey/partials/reservations_legend.html
src/nyc_trees/apps/survey/templates/survey/progress.html
src/nyc_trees/apps/survey/templates/survey/reserve_blockface_confirmation.html
src/nyc_trees/apps/users/templates/groups/detail.html
src/nyc_trees/apps/users/templates/groups/list.html
src/nyc_trees/apps/users/templates/users/achievement.html
src/nyc_trees/apps/users/templates/users/partials/profile/reservations.html
src/nyc_trees/apps/users/tests.py
src/nyc_trees/templates/registration/activation_email.html
src/nyc_trees/templates/registration/activation_email.txt
src/nyc_trees/templates/registration/registration_form.html

Implement text changes requests by Parks.

---

src/nyc_trees/apps/home/templates/home/about_faq.html
src/nyc_trees/apps/home/templates/home/partials/dashboard.html
src/nyc_trees/apps/home/templates/home/partials/training.html
src/nyc_trees/apps/survey/templates/survey/partials/progress_legend.html
src/nyc_trees/apps/survey/templates/survey/reserve_blockface_confirmation.html
src/nyc_trees/apps/survey/templates/survey/survey.html
src/nyc_trees/apps/users/models.py
src/nyc_trees/templates/registration/activation_email.html
src/nyc_trees/templates/registration/activation_email.txt

Implement final text changes from Parks

---

src/nyc_trees/sass/partials/_header.scss

added a high z-index to fix #1873

---

src/nyc_trees/sass/partials/_map.scss
src/nyc_trees/sass/partials/_survey.scss

fixes #1875 where map wasnt going to bottom of container

---

deployment/ansible/services.yml
src/nyc_trees/apps/users/models.py

I also removed a few out-dated comments about hard-coded URLs.
Connects to #1882

Update achievement descriptions and rewards.

---

deployment/ansible/group_vars/all

I needed to make this change to be able to provision a development environment from scratch.

Update to newest version of OpenJDK 7

---

src/nyc_trees/apps/core/templates/base.html
src/nyc_trees/apps/core/templates/core/partials/nav.html
src/nyc_trees/apps/home/templates/home/about_faq.html
src/nyc_trees/apps/home/templates/home/partials/dashboard.html
src/nyc_trees/apps/home/templates/home/partials/home_public.html
src/nyc_trees/apps/home/tests.py
src/nyc_trees/apps/login/uitests.py
src/nyc_trees/apps/login/urls/accounts.py
src/nyc_trees/apps/survey/templates/survey/partials/progress_legend.html
src/nyc_trees/templates/registration/login.html

- Removes the registration page and any links to it
- Removes the progress bubbles and tree "ticker" on the homepage
- Changes text throughout the site
Connects to #1885

Implement final text and other changes.

---

src/nyc_trees/apps/survey/templates/survey/partials/progress_legend.html

Further text changes
